// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 订单公共字段
type OrderCommon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	OrderState    int32                  `protobuf:"varint,3,opt,name=orderState,proto3" json:"orderState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCommon) Reset() {
	*x = OrderCommon{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCommon) ProtoMessage() {}

func (x *OrderCommon) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCommon.ProtoReflect.Descriptor instead.
func (*OrderCommon) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCommon) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderCommon) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderCommon) GetOrderState() int32 {
	if x != nil {
		return x.OrderState
	}
	return 0
}

// 订单支付提交请求
type OrderCommitPayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	PayId         int64                  `protobuf:"varint,2,opt,name=payId,proto3" json:"payId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCommitPayReq) Reset() {
	*x = OrderCommitPayReq{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCommitPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCommitPayReq) ProtoMessage() {}

func (x *OrderCommitPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCommitPayReq.ProtoReflect.Descriptor instead.
func (*OrderCommitPayReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCommitPayReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderCommitPayReq) GetPayId() int64 {
	if x != nil {
		return x.PayId
	}
	return 0
}

// 订单支付提交响应
type OrderCommitPayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCommitPayResp) Reset() {
	*x = OrderCommitPayResp{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCommitPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCommitPayResp) ProtoMessage() {}

func (x *OrderCommitPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCommitPayResp.ProtoReflect.Descriptor instead.
func (*OrderCommitPayResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCommitPayResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// 订单状态检测请求
type OrderStateCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	OrderState    int32                  `protobuf:"varint,2,opt,name=orderState,proto3" json:"orderState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStateCheckReq) Reset() {
	*x = OrderStateCheckReq{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStateCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStateCheckReq) ProtoMessage() {}

func (x *OrderStateCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStateCheckReq.ProtoReflect.Descriptor instead.
func (*OrderStateCheckReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderStateCheckReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderStateCheckReq) GetOrderState() int32 {
	if x != nil {
		return x.OrderState
	}
	return 0
}

// 订单状态检测响应
type OrderStateCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderCommon   *OrderCommon           `protobuf:"bytes,1,opt,name=orderCommon,proto3" json:"orderCommon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStateCheckResp) Reset() {
	*x = OrderStateCheckResp{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStateCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStateCheckResp) ProtoMessage() {}

func (x *OrderStateCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStateCheckResp.ProtoReflect.Descriptor instead.
func (*OrderStateCheckResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderStateCheckResp) GetOrderCommon() *OrderCommon {
	if x != nil {
		return x.OrderCommon
	}
	return nil
}

// 创建订单请求
type CreateOrderReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderNo        string                 `protobuf:"bytes,2,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	OrderPrice     int64                  `protobuf:"varint,3,opt,name=orderPrice,proto3" json:"orderPrice,omitempty"`
	OrderDes       string                 `protobuf:"bytes,4,opt,name=orderDes,proto3" json:"orderDes,omitempty"`
	OrderBeginTime int64                  `protobuf:"varint,5,opt,name=orderBeginTime,proto3" json:"orderBeginTime,omitempty"`
	OrderEndTime   int64                  `protobuf:"varint,6,opt,name=orderEndTime,proto3" json:"orderEndTime,omitempty"`
	SkuId          int64                  `protobuf:"varint,7,opt,name=skuId,proto3" json:"skuId,omitempty"`       // 商品 SKU ID（用于 Saga 扣减库存）
	Quantity       int64                  `protobuf:"varint,8,opt,name=quantity,proto3" json:"quantity,omitempty"` // 商品数量（用于 Saga 扣减库存）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateOrderReq) GetOrderPrice() int64 {
	if x != nil {
		return x.OrderPrice
	}
	return 0
}

func (x *CreateOrderReq) GetOrderDes() string {
	if x != nil {
		return x.OrderDes
	}
	return ""
}

func (x *CreateOrderReq) GetOrderBeginTime() int64 {
	if x != nil {
		return x.OrderBeginTime
	}
	return 0
}

func (x *CreateOrderReq) GetOrderEndTime() int64 {
	if x != nil {
		return x.OrderEndTime
	}
	return 0
}

func (x *CreateOrderReq) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CreateOrderReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// 创建订单响应
type CreateOrderRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRsp) Reset() {
	*x = CreateOrderRsp{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRsp) ProtoMessage() {}

func (x *CreateOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRsp.ProtoReflect.Descriptor instead.
func (*CreateOrderRsp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOrderRsp) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// 取消订单请求
type CancelOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	SkuId         int64                  `protobuf:"varint,2,opt,name=skuId,proto3" json:"skuId,omitempty"`       // 商品 SKU ID（用于 Saga 回滚库存）
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"` // 商品数量（用于 Saga 回滚库存）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *CancelOrderReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CancelOrderReq) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CancelOrderReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// 取消订单响应
type CancelOrderRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRsp) Reset() {
	*x = CancelOrderRsp{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRsp) ProtoMessage() {}

func (x *CancelOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRsp.ProtoReflect.Descriptor instead.
func (*CancelOrderRsp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *CancelOrderRsp) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"a\n" +
	"\vOrderCommon\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x03R\aorderId\x12\x18\n" +
	"\aorderNo\x18\x02 \x01(\tR\aorderNo\x12\x1e\n" +
	"\n" +
	"orderState\x18\x03 \x01(\x05R\n" +
	"orderState\"C\n" +
	"\x11OrderCommitPayReq\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x03R\aorderId\x12\x14\n" +
	"\x05payId\x18\x02 \x01(\x03R\x05payId\"$\n" +
	"\x12OrderCommitPayResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"N\n" +
	"\x12OrderStateCheckReq\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x03R\aorderId\x12\x1e\n" +
	"\n" +
	"orderState\x18\x02 \x01(\x05R\n" +
	"orderState\"K\n" +
	"\x13OrderStateCheckResp\x124\n" +
	"\vorderCommon\x18\x01 \x01(\v2\x12.order.OrderCommonR\vorderCommon\"\xfc\x01\n" +
	"\x0eCreateOrderReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\aorderNo\x18\x02 \x01(\tR\aorderNo\x12\x1e\n" +
	"\n" +
	"orderPrice\x18\x03 \x01(\x03R\n" +
	"orderPrice\x12\x1a\n" +
	"\borderDes\x18\x04 \x01(\tR\borderDes\x12&\n" +
	"\x0eorderBeginTime\x18\x05 \x01(\x03R\x0eorderBeginTime\x12\"\n" +
	"\forderEndTime\x18\x06 \x01(\x03R\forderEndTime\x12\x14\n" +
	"\x05skuId\x18\a \x01(\x03R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x03R\bquantity\"*\n" +
	"\x0eCreateOrderRsp\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x03R\aorderId\"\\\n" +
	"\x0eCancelOrderReq\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\x03R\aOrderId\x12\x14\n" +
	"\x05skuId\x18\x02 \x01(\x03R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"*\n" +
	"\x0eCancelOrderRsp\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\x03R\aOrderId2\x92\x02\n" +
	"\x05Order\x12E\n" +
	"\x0eOrderCommitPay\x12\x18.order.OrderCommitPayReq\x1a\x19.order.OrderCommitPayResp\x12H\n" +
	"\x0fOrderStateCheck\x12\x19.order.OrderStateCheckReq\x1a\x1a.order.OrderStateCheckResp\x12;\n" +
	"\vCreateOrder\x12\x15.order.CreateOrderReq\x1a\x15.order.CreateOrderRsp\x12;\n" +
	"\vCancelOrder\x12\x15.order.CancelOrderReq\x1a\x15.order.CancelOrderRspB\tZ\a./orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_order_proto_goTypes = []any{
	(*OrderCommon)(nil),         // 0: order.OrderCommon
	(*OrderCommitPayReq)(nil),   // 1: order.OrderCommitPayReq
	(*OrderCommitPayResp)(nil),  // 2: order.OrderCommitPayResp
	(*OrderStateCheckReq)(nil),  // 3: order.OrderStateCheckReq
	(*OrderStateCheckResp)(nil), // 4: order.OrderStateCheckResp
	(*CreateOrderReq)(nil),      // 5: order.CreateOrderReq
	(*CreateOrderRsp)(nil),      // 6: order.CreateOrderRsp
	(*CancelOrderReq)(nil),      // 7: order.CancelOrderReq
	(*CancelOrderRsp)(nil),      // 8: order.CancelOrderRsp
}
var file_order_proto_depIdxs = []int32{
	0, // 0: order.OrderStateCheckResp.orderCommon:type_name -> order.OrderCommon
	1, // 1: order.Order.OrderCommitPay:input_type -> order.OrderCommitPayReq
	3, // 2: order.Order.OrderStateCheck:input_type -> order.OrderStateCheckReq
	5, // 3: order.Order.CreateOrder:input_type -> order.CreateOrderReq
	7, // 4: order.Order.CancelOrder:input_type -> order.CancelOrderReq
	2, // 5: order.Order.OrderCommitPay:output_type -> order.OrderCommitPayResp
	4, // 6: order.Order.OrderStateCheck:output_type -> order.OrderStateCheckResp
	6, // 7: order.Order.CreateOrder:output_type -> order.CreateOrderRsp
	8, // 8: order.Order.CancelOrder:output_type -> order.CancelOrderRsp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
