// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Order_OrderCommitPay_FullMethodName  = "/order.Order/OrderCommitPay"
	Order_OrderStateCheck_FullMethodName = "/order.Order/OrderStateCheck"
	Order_CreateOrder_FullMethodName     = "/order.Order/CreateOrder"
	Order_CancelOrder_FullMethodName     = "/order.Order/CancelOrder"
	Order_TccTryOrder_FullMethodName     = "/order.Order/TccTryOrder"
	Order_TccConfirmOrder_FullMethodName = "/order.Order/TccConfirmOrder"
	Order_TccCancelOrder_FullMethodName  = "/order.Order/TccCancelOrder"
)

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 订单服务
type OrderClient interface {
	// 订单支付提交
	OrderCommitPay(ctx context.Context, in *OrderCommitPayReq, opts ...grpc.CallOption) (*OrderCommitPayResp, error)
	// 订单状态检测
	OrderStateCheck(ctx context.Context, in *OrderStateCheckReq, opts ...grpc.CallOption) (*OrderStateCheckResp, error)
	// 创建订单
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderRsp, error)
	// 取消订单
	CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderRsp, error)
	// TCC Try：预留订单资源（由业务方/编排层在 Try 阶段调用）
	TccTryOrder(ctx context.Context, in *TccTryOrderReq, opts ...grpc.CallOption) (*TccTryOrderResp, error)
	// TCC Confirm：确认订单（由 DTM 在 Confirm 阶段回调）
	TccConfirmOrder(ctx context.Context, in *TccConfirmOrderReq, opts ...grpc.CallOption) (*TccConfirmOrderResp, error)
	// TCC Cancel：回滚订单（由 DTM 在 Cancel 阶段回调）
	TccCancelOrder(ctx context.Context, in *TccCancelOrderReq, opts ...grpc.CallOption) (*TccCancelOrderResp, error)
}

type orderClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderClient(cc grpc.ClientConnInterface) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) OrderCommitPay(ctx context.Context, in *OrderCommitPayReq, opts ...grpc.CallOption) (*OrderCommitPayResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderCommitPayResp)
	err := c.cc.Invoke(ctx, Order_OrderCommitPay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) OrderStateCheck(ctx context.Context, in *OrderStateCheckReq, opts ...grpc.CallOption) (*OrderStateCheckResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderStateCheckResp)
	err := c.cc.Invoke(ctx, Order_OrderStateCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderRsp)
	err := c.cc.Invoke(ctx, Order_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderRsp)
	err := c.cc.Invoke(ctx, Order_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) TccTryOrder(ctx context.Context, in *TccTryOrderReq, opts ...grpc.CallOption) (*TccTryOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TccTryOrderResp)
	err := c.cc.Invoke(ctx, Order_TccTryOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) TccConfirmOrder(ctx context.Context, in *TccConfirmOrderReq, opts ...grpc.CallOption) (*TccConfirmOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TccConfirmOrderResp)
	err := c.cc.Invoke(ctx, Order_TccConfirmOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) TccCancelOrder(ctx context.Context, in *TccCancelOrderReq, opts ...grpc.CallOption) (*TccCancelOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TccCancelOrderResp)
	err := c.cc.Invoke(ctx, Order_TccCancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
// All implementations must embed UnimplementedOrderServer
// for forward compatibility.
//
// 订单服务
type OrderServer interface {
	// 订单支付提交
	OrderCommitPay(context.Context, *OrderCommitPayReq) (*OrderCommitPayResp, error)
	// 订单状态检测
	OrderStateCheck(context.Context, *OrderStateCheckReq) (*OrderStateCheckResp, error)
	// 创建订单
	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderRsp, error)
	// 取消订单
	CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderRsp, error)
	// TCC Try：预留订单资源（由业务方/编排层在 Try 阶段调用）
	TccTryOrder(context.Context, *TccTryOrderReq) (*TccTryOrderResp, error)
	// TCC Confirm：确认订单（由 DTM 在 Confirm 阶段回调）
	TccConfirmOrder(context.Context, *TccConfirmOrderReq) (*TccConfirmOrderResp, error)
	// TCC Cancel：回滚订单（由 DTM 在 Cancel 阶段回调）
	TccCancelOrder(context.Context, *TccCancelOrderReq) (*TccCancelOrderResp, error)
	mustEmbedUnimplementedOrderServer()
}

// UnimplementedOrderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServer struct{}

func (UnimplementedOrderServer) OrderCommitPay(context.Context, *OrderCommitPayReq) (*OrderCommitPayResp, error) {
	return nil, status.Error(codes.Unimplemented, "method OrderCommitPay not implemented")
}
func (UnimplementedOrderServer) OrderStateCheck(context.Context, *OrderStateCheckReq) (*OrderStateCheckResp, error) {
	return nil, status.Error(codes.Unimplemented, "method OrderStateCheck not implemented")
}
func (UnimplementedOrderServer) CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderServer) CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedOrderServer) TccTryOrder(context.Context, *TccTryOrderReq) (*TccTryOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TccTryOrder not implemented")
}
func (UnimplementedOrderServer) TccConfirmOrder(context.Context, *TccConfirmOrderReq) (*TccConfirmOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TccConfirmOrder not implemented")
}
func (UnimplementedOrderServer) TccCancelOrder(context.Context, *TccCancelOrderReq) (*TccCancelOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TccCancelOrder not implemented")
}
func (UnimplementedOrderServer) mustEmbedUnimplementedOrderServer() {}
func (UnimplementedOrderServer) testEmbeddedByValue()               {}

// UnsafeOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServer will
// result in compilation errors.
type UnsafeOrderServer interface {
	mustEmbedUnimplementedOrderServer()
}

func RegisterOrderServer(s grpc.ServiceRegistrar, srv OrderServer) {
	// If the following call panics, it indicates UnimplementedOrderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Order_ServiceDesc, srv)
}

func _Order_OrderCommitPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCommitPayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).OrderCommitPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_OrderCommitPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).OrderCommitPay(ctx, req.(*OrderCommitPayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_OrderStateCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderStateCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).OrderStateCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_OrderStateCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).OrderStateCheck(ctx, req.(*OrderStateCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrder(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CancelOrder(ctx, req.(*CancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_TccTryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TccTryOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).TccTryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_TccTryOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).TccTryOrder(ctx, req.(*TccTryOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_TccConfirmOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TccConfirmOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).TccConfirmOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_TccConfirmOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).TccConfirmOrder(ctx, req.(*TccConfirmOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_TccCancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TccCancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).TccCancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_TccCancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).TccCancelOrder(ctx, req.(*TccCancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Order_ServiceDesc is the grpc.ServiceDesc for Order service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Order_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderCommitPay",
			Handler:    _Order_OrderCommitPay_Handler,
		},
		{
			MethodName: "OrderStateCheck",
			Handler:    _Order_OrderStateCheck_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Order_CreateOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Order_CancelOrder_Handler,
		},
		{
			MethodName: "TccTryOrder",
			Handler:    _Order_TccTryOrder_Handler,
		},
		{
			MethodName: "TccConfirmOrder",
			Handler:    _Order_TccConfirmOrder_Handler,
		},
		{
			MethodName: "TccCancelOrder",
			Handler:    _Order_TccCancelOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
