// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"user-rpc/internal/logic"
	"user-rpc/internal/svc"
	"user-rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 用户登录
func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 用户登出
func (s *UserServer) Logout(ctx context.Context, in *user.LogoutReq) (*user.LogoutResp, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

// 创建用户
func (s *UserServer) CreateUser(ctx context.Context, in *user.CreateOrUpdateUserReq) (*user.CreateOrUpdateUserResp, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

// 更新用户信息
func (s *UserServer) UpdateUser(ctx context.Context, in *user.CreateOrUpdateUserReq) (*user.CreateOrUpdateUserResp, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

// 微信小程序登录
func (s *UserServer) WxMiniProgramLogin(ctx context.Context, in *user.WxMiniProgramLoginReq) (*user.WxMiniProgramLoginResp, error) {
	l := logic.NewWxMiniProgramLoginLogic(ctx, s.svcCtx)
	return l.WxMiniProgramLogin(in)
}

// 刷新token
func (s *UserServer) RefreshToken(ctx context.Context, in *user.RefreshTokenReq) (*user.RefreshTokenResp, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

// 用户列表
func (s *UserServer) UserList(ctx context.Context, in *user.UserListReq) (*user.UserListResp, error) {
	l := logic.NewUserListLogic(ctx, s.svcCtx)
	return l.UserList(in)
}

// 用户详情查询
func (s *UserServer) UserInfo(ctx context.Context, in *user.UserInfoReq) (*user.UserInfoRsp, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
