// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: stock.proto

package stock_client

import (
	"context"

	"stock-rpc/stock"

	"google.golang.org/protobuf/types/known/emptypb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchQueryStockReq       = stock.BatchQueryStockReq
	BatchQueryStockResp      = stock.BatchQueryStockResp
	QueryStockReq            = stock.QueryStockReq
	QueryStockResp           = stock.QueryStockResp
	StockInfo                = stock.StockInfo
	TccCancelDeductStockReq  = stock.TccCancelDeductStockReq
	TccConfirmDeductStockReq = stock.TccConfirmDeductStockReq
	TccTryDeductStockReq     = stock.TccTryDeductStockReq

	Stock interface {
		// 批量查询商品库存
		BatchQueryStock(ctx context.Context, in *BatchQueryStockReq, opts ...grpc.CallOption) (*BatchQueryStockResp, error)
		// TCC Try：冻结库存（dtm TCC 全局事务 Try 阶段调用，预留资源）
		TccTryDeductStock(ctx context.Context, in *TccTryDeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
		// TCC Confirm：确认扣减库存（dtm TCC 全局事务 Confirm 阶段回调）
		TccConfirmDeductStock(ctx context.Context, in *TccConfirmDeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
		// TCC Cancel：释放库存（dtm TCC 全局事务 Cancel 阶段回调）
		TccCancelDeductStock(ctx context.Context, in *TccCancelDeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	}

	defaultStock struct {
		cli zrpc.Client
	}
)

func NewStock(cli zrpc.Client) Stock {
	return &defaultStock{
		cli: cli,
	}
}

// 批量查询商品库存
func (m *defaultStock) BatchQueryStock(ctx context.Context, in *BatchQueryStockReq, opts ...grpc.CallOption) (*BatchQueryStockResp, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.BatchQueryStock(ctx, in, opts...)
}

// TCC Try：冻结库存（dtm TCC 全局事务 Try 阶段调用，预留资源）
func (m *defaultStock) TccTryDeductStock(ctx context.Context, in *TccTryDeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.TccTryDeductStock(ctx, in, opts...)
}

// TCC Confirm：确认扣减库存（dtm TCC 全局事务 Confirm 阶段回调）
func (m *defaultStock) TccConfirmDeductStock(ctx context.Context, in *TccConfirmDeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.TccConfirmDeductStock(ctx, in, opts...)
}

// TCC Cancel：释放库存（dtm TCC 全局事务 Cancel 阶段回调）
func (m *defaultStock) TccCancelDeductStock(ctx context.Context, in *TccCancelDeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.TccCancelDeductStock(ctx, in, opts...)
}
