// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateOrUpdateUserReq struct {
	UserId   int64  `json:"userId,optional"`
	Mobile   string `json:"mobile"`
	NickName string `json:"nickName"`
	Sex      int    `json:"sex,options=0|1|2"`
	Avatar   string `json:"avatar,optional"`
	Password string `json:"password"`
	Email    string `json:"email,optional"`
}

type CreateOrUpdateUserResp struct {
	UserId int64 `json:"userId"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
	UserId       int64  `json:"userId"`
}

type LogoutReq struct {
	UserId int64 `json:"userId"`
}

type LogoutResp struct {
	Ok bool `json:"ok"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserInfo struct {
	UserId    int64  `json:"userId"`
	Mobile    string `json:"mobile"`
	NickName  string `json:"nickName"`
	Sex       int    `json:"sex"`
	Avatar    string `json:"avatar"`
	Email     string `json:"email"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type UserInfoReq struct {
	UserId int64 `json:"userId"`
}

type UserListReq struct {
	Page     int    `json:"page,default=1"`
	PageSize int    `json:"pageSize,default=10"`
	Mobile   string `json:"mobile,optional"`
	NickName string `json:"nickName,optional"`
}

type UserListResp struct {
	List  []UserInfo `json:"list"`
	Total int        `json:"total"`
}

type WxMiniProgramLoginReq struct {
	Code     string `json:"code"`
	NickName string `json:"nickName,optional"`
	Avatar   string `json:"avatar,optional"`
	Sex      int    `json:"sex,optional,options=0|1|2"`
}

type WxMiniProgramLoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
	UserId       int64  `json:"userId"`
	SessionKey   string `json:"sessionKey,optional"`
	OpenId       string `json:"openId,optional"`
}
