// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package user_client

import (
	"context"

	"user-rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOrUpdateUserReq  = user.CreateOrUpdateUserReq
	CreateOrUpdateUserResp = user.CreateOrUpdateUserResp
	LoginReq               = user.LoginReq
	LoginResp              = user.LoginResp
	LogoutReq              = user.LogoutReq
	LogoutResp             = user.LogoutResp
	RefreshTokenReq        = user.RefreshTokenReq
	RefreshTokenResp       = user.RefreshTokenResp
	UserInfoReq            = user.UserInfoReq
	UserInfoRsp            = user.UserInfoRsp
	UserListReq            = user.UserListReq
	UserListResp           = user.UserListResp
	WxMiniProgramLoginReq  = user.WxMiniProgramLoginReq
	WxMiniProgramLoginResp = user.WxMiniProgramLoginResp

	User interface {
		// 用户登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// 用户登出
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error)
		// 创建用户
		CreateUser(ctx context.Context, in *CreateOrUpdateUserReq, opts ...grpc.CallOption) (*CreateOrUpdateUserResp, error)
		// 更新用户信息
		UpdateUser(ctx context.Context, in *CreateOrUpdateUserReq, opts ...grpc.CallOption) (*CreateOrUpdateUserResp, error)
		// 微信小程序登录
		WxMiniProgramLogin(ctx context.Context, in *WxMiniProgramLoginReq, opts ...grpc.CallOption) (*WxMiniProgramLoginResp, error)
		// 刷新token
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
		// 用户列表
		UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error)
		// 用户详情查询
		UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoRsp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 用户登录
func (m *defaultUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 用户登出
func (m *defaultUser) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

// 创建用户
func (m *defaultUser) CreateUser(ctx context.Context, in *CreateOrUpdateUserReq, opts ...grpc.CallOption) (*CreateOrUpdateUserResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

// 更新用户信息
func (m *defaultUser) UpdateUser(ctx context.Context, in *CreateOrUpdateUserReq, opts ...grpc.CallOption) (*CreateOrUpdateUserResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

// 微信小程序登录
func (m *defaultUser) WxMiniProgramLogin(ctx context.Context, in *WxMiniProgramLoginReq, opts ...grpc.CallOption) (*WxMiniProgramLoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.WxMiniProgramLogin(ctx, in, opts...)
}

// 刷新token
func (m *defaultUser) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

// 用户列表
func (m *defaultUser) UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UserList(ctx, in, opts...)
}

// 用户详情查询
func (m *defaultUser) UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoRsp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}
