// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: stock.proto

package server

import (
	"context"

	"google.golang.org/protobuf/types/known/emptypb"
	"stock-rpc/internal/logic"
	"stock-rpc/internal/svc"
	"stock-rpc/stock"
)

type StockServer struct {
	svcCtx *svc.ServiceContext
	stock.UnimplementedStockServer
}

func NewStockServer(svcCtx *svc.ServiceContext) *StockServer {
	return &StockServer{
		svcCtx: svcCtx,
	}
}

// Saga 正向：扣减库存（dtm Saga 全局事务中调用的 Action 分支）
func (s *StockServer) DeductStock(ctx context.Context, in *stock.DeductStockReq) (*emptypb.Empty, error) {
	l := logic.NewDeductStockLogic(ctx, s.svcCtx)
	return l.DeductStock(in)
}

// Saga 补偿：回滚库存（dtm Saga 全局事务失败时调用的 Compensate 分支）
func (s *StockServer) RollbackStock(ctx context.Context, in *stock.RollbackStockReq) (*emptypb.Empty, error) {
	l := logic.NewRollbackStockLogic(ctx, s.svcCtx)
	return l.RollbackStock(in)
}

// 查询单个商品库存
func (s *StockServer) QueryStock(ctx context.Context, in *stock.QueryStockReq) (*stock.QueryStockResp, error) {
	l := logic.NewQueryStockLogic(ctx, s.svcCtx)
	return l.QueryStock(in)
}

// 批量查询商品库存
func (s *StockServer) BatchQueryStock(ctx context.Context, in *stock.BatchQueryStockReq) (*stock.BatchQueryStockResp, error) {
	l := logic.NewBatchQueryStockLogic(ctx, s.svcCtx)
	return l.BatchQueryStock(in)
}

// TCC Try：冻结库存（dtm TCC 全局事务 Try 阶段调用，预留资源）
func (s *StockServer) TccTryDeductStock(ctx context.Context, in *stock.TccTryDeductStockReq) (*emptypb.Empty, error) {
	l := logic.NewTccTryDeductStockLogic(ctx, s.svcCtx)
	return l.TccTryDeductStock(in)
}

// TCC Confirm：确认扣减库存（dtm TCC 全局事务 Confirm 阶段回调）
func (s *StockServer) TccConfirmDeductStock(ctx context.Context, in *stock.TccConfirmDeductStockReq) (*emptypb.Empty, error) {
	l := logic.NewTccConfirmDeductStockLogic(ctx, s.svcCtx)
	return l.TccConfirmDeductStock(in)
}

// TCC Cancel：释放库存（dtm TCC 全局事务 Cancel 阶段回调）
func (s *StockServer) TccCancelDeductStock(ctx context.Context, in *stock.TccCancelDeductStockReq) (*emptypb.Empty, error) {
	l := logic.NewTccCancelDeductStockLogic(ctx, s.svcCtx)
	return l.TccCancelDeductStock(in)
}
