// Code generated by goctl. DO NOT EDIT.
// Source: stock.proto

package server

import (
	"context"

	"stock-rpc/internal/logic"
	"stock-rpc/internal/svc"
	"stock-rpc/stock"

	"google.golang.org/protobuf/types/known/emptypb"
)

type StockServer struct {
	svcCtx *svc.ServiceContext
	stock.UnimplementedStockServer
}

func NewStockServer(svcCtx *svc.ServiceContext) *StockServer {
	return &StockServer{
		svcCtx: svcCtx,
	}
}

// Saga 正向：扣减库存
func (s *StockServer) DeductStock(ctx context.Context, in *stock.DeductStockReq) (*emptypb.Empty, error) {
	l := logic.NewDeductStockLogic(ctx, s.svcCtx)
	return l.DeductStock(in)
}

// Saga 补偿：回滚库存
func (s *StockServer) RollbackStock(ctx context.Context, in *stock.RollbackStockReq) (*emptypb.Empty, error) {
	l := logic.NewRollbackStockLogic(ctx, s.svcCtx)
	return l.RollbackStock(in)
}

// 查询单个商品库存
func (s *StockServer) QueryStock(ctx context.Context, in *stock.QueryStockReq) (*stock.QueryStockResp, error) {
	l := logic.NewQueryStockLogic(ctx, s.svcCtx)
	return l.QueryStock(in)
}

// 批量查询商品库存
func (s *StockServer) BatchQueryStock(ctx context.Context, in *stock.BatchQueryStockReq) (*stock.BatchQueryStockResp, error) {
	l := logic.NewBatchQueryStockLogic(ctx, s.svcCtx)
	return l.BatchQueryStock(in)
}
