// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: cronjob.proto

package cronjob

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务目标类型
type TargetType int32

const (
	TargetType_GRPC TargetType = 0
	TargetType_HTTP TargetType = 1
)

// Enum value maps for TargetType.
var (
	TargetType_name = map[int32]string{
		0: "GRPC",
		1: "HTTP",
	}
	TargetType_value = map[string]int32{
		"GRPC": 0,
		"HTTP": 1,
	}
)

func (x TargetType) Enum() *TargetType {
	p := new(TargetType)
	*p = x
	return p
}

func (x TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_cronjob_proto_enumTypes[0].Descriptor()
}

func (TargetType) Type() protoreflect.EnumType {
	return &file_cronjob_proto_enumTypes[0]
}

func (x TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetType.Descriptor instead.
func (TargetType) EnumDescriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{0}
}

// 任务状态
type TaskStatus int32

const (
	TaskStatus_TASK_DISABLED TaskStatus = 0
	TaskStatus_TASK_ENABLED  TaskStatus = 1
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_DISABLED",
		1: "TASK_ENABLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_DISABLED": 0,
		"TASK_ENABLED":  1,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cronjob_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_cronjob_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{1}
}

// 执行状态
type ExecStatus int32

const (
	ExecStatus_PENDING  ExecStatus = 0
	ExecStatus_RUNNING  ExecStatus = 1
	ExecStatus_SUCCESS  ExecStatus = 2
	ExecStatus_FAILED   ExecStatus = 3
	ExecStatus_RETRYING ExecStatus = 4
)

// Enum value maps for ExecStatus.
var (
	ExecStatus_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "SUCCESS",
		3: "FAILED",
		4: "RETRYING",
	}
	ExecStatus_value = map[string]int32{
		"PENDING":  0,
		"RUNNING":  1,
		"SUCCESS":  2,
		"FAILED":   3,
		"RETRYING": 4,
	}
)

func (x ExecStatus) Enum() *ExecStatus {
	p := new(ExecStatus)
	*p = x
	return p
}

func (x ExecStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cronjob_proto_enumTypes[2].Descriptor()
}

func (ExecStatus) Type() protoreflect.EnumType {
	return &file_cronjob_proto_enumTypes[2]
}

func (x ExecStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecStatus.Descriptor instead.
func (ExecStatus) EnumDescriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{2}
}

// 重试策略
type RetryPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxRetries    int32                  `protobuf:"varint,1,opt,name=maxRetries,proto3" json:"maxRetries,omitempty"`   // 最大重试次数
	IntervalSec   int32                  `protobuf:"varint,2,opt,name=intervalSec,proto3" json:"intervalSec,omitempty"` // 重试间隔（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_cronjob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{0}
}

func (x *RetryPolicy) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *RetryPolicy) GetIntervalSec() int32 {
	if x != nil {
		return x.IntervalSec
	}
	return 0
}

// 注册任务请求
type RegisterTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                      // 任务名称（唯一标识）
	CronExpr      string                 `protobuf:"bytes,2,opt,name=cronExpr,proto3" json:"cronExpr,omitempty"`                              // Cron 表达式
	TargetType    TargetType             `protobuf:"varint,3,opt,name=targetType,proto3,enum=cronjob.TargetType" json:"targetType,omitempty"` // 目标类型
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`                                  // 目标地址 (gRPC: "service/method" 或 HTTP: "http://host/path")
	RequestBody   string                 `protobuf:"bytes,5,opt,name=requestBody,proto3" json:"requestBody,omitempty"`                        // 请求体 JSON
	RetryPolicy   *RetryPolicy           `protobuf:"bytes,6,opt,name=retryPolicy,proto3" json:"retryPolicy,omitempty"`                        // 重试策略
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`                        // 描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTaskReq) Reset() {
	*x = RegisterTaskReq{}
	mi := &file_cronjob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskReq) ProtoMessage() {}

func (x *RegisterTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskReq.ProtoReflect.Descriptor instead.
func (*RegisterTaskReq) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterTaskReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterTaskReq) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *RegisterTaskReq) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_GRPC
}

func (x *RegisterTaskReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RegisterTaskReq) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

func (x *RegisterTaskReq) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

func (x *RegisterTaskReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 注册任务响应
type RegisterTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTaskResp) Reset() {
	*x = RegisterTaskResp{}
	mi := &file_cronjob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskResp) ProtoMessage() {}

func (x *RegisterTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskResp.ProtoReflect.Descriptor instead.
func (*RegisterTaskResp) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterTaskResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// 注销任务请求
type UnregisterTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterTaskReq) Reset() {
	*x = UnregisterTaskReq{}
	mi := &file_cronjob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterTaskReq) ProtoMessage() {}

func (x *UnregisterTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterTaskReq.ProtoReflect.Descriptor instead.
func (*UnregisterTaskReq) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterTaskReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 注销任务响应
type UnregisterTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterTaskResp) Reset() {
	*x = UnregisterTaskResp{}
	mi := &file_cronjob_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterTaskResp) ProtoMessage() {}

func (x *UnregisterTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterTaskResp.ProtoReflect.Descriptor instead.
func (*UnregisterTaskResp) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterTaskResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// 任务信息
type TaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CronExpr      string                 `protobuf:"bytes,2,opt,name=cronExpr,proto3" json:"cronExpr,omitempty"`
	TargetType    TargetType             `protobuf:"varint,3,opt,name=targetType,proto3,enum=cronjob.TargetType" json:"targetType,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	RequestBody   string                 `protobuf:"bytes,5,opt,name=requestBody,proto3" json:"requestBody,omitempty"`
	RetryPolicy   *RetryPolicy           `protobuf:"bytes,6,opt,name=retryPolicy,proto3" json:"retryPolicy,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Status        TaskStatus             `protobuf:"varint,8,opt,name=status,proto3,enum=cronjob.TaskStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_cronjob_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{5}
}

func (x *TaskInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskInfo) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *TaskInfo) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_GRPC
}

func (x *TaskInfo) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TaskInfo) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

func (x *TaskInfo) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

func (x *TaskInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskInfo) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_DISABLED
}

func (x *TaskInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TaskInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 列举任务请求
type ListTasksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksReq) Reset() {
	*x = ListTasksReq{}
	mi := &file_cronjob_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksReq) ProtoMessage() {}

func (x *ListTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksReq.ProtoReflect.Descriptor instead.
func (*ListTasksReq) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{6}
}

func (x *ListTasksReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTasksReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 列举任务响应
type ListTasksResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskInfo            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResp) Reset() {
	*x = ListTasksResp{}
	mi := &file_cronjob_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResp) ProtoMessage() {}

func (x *ListTasksResp) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResp.ProtoReflect.Descriptor instead.
func (*ListTasksResp) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{7}
}

func (x *ListTasksResp) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 执行记录
type ExecutionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskName      string                 `protobuf:"bytes,2,opt,name=taskName,proto3" json:"taskName,omitempty"`
	ScheduledAt   int64                  `protobuf:"varint,3,opt,name=scheduledAt,proto3" json:"scheduledAt,omitempty"`
	StartedAt     int64                  `protobuf:"varint,4,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	FinishedAt    int64                  `protobuf:"varint,5,opt,name=finishedAt,proto3" json:"finishedAt,omitempty"`
	Status        ExecStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=cronjob.ExecStatus" json:"status,omitempty"`
	RetryCount    int32                  `protobuf:"varint,7,opt,name=retryCount,proto3" json:"retryCount,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,8,opt,name=maxRetries,proto3" json:"maxRetries,omitempty"`
	Result        string                 `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`
	TraceId       string                 `protobuf:"bytes,10,opt,name=traceId,proto3" json:"traceId,omitempty"`
	ExecNode      string                 `protobuf:"bytes,11,opt,name=execNode,proto3" json:"execNode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionRecord) Reset() {
	*x = ExecutionRecord{}
	mi := &file_cronjob_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRecord) ProtoMessage() {}

func (x *ExecutionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRecord.ProtoReflect.Descriptor instead.
func (*ExecutionRecord) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{8}
}

func (x *ExecutionRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExecutionRecord) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *ExecutionRecord) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *ExecutionRecord) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ExecutionRecord) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *ExecutionRecord) GetStatus() ExecStatus {
	if x != nil {
		return x.Status
	}
	return ExecStatus_PENDING
}

func (x *ExecutionRecord) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *ExecutionRecord) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *ExecutionRecord) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecutionRecord) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ExecutionRecord) GetExecNode() string {
	if x != nil {
		return x.ExecNode
	}
	return ""
}

// 列举执行历史请求
type ListExecutionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskName      string                 `protobuf:"bytes,1,opt,name=taskName,proto3" json:"taskName,omitempty"`
	Status        ExecStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=cronjob.ExecStatus" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsReq) Reset() {
	*x = ListExecutionsReq{}
	mi := &file_cronjob_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsReq) ProtoMessage() {}

func (x *ListExecutionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsReq.ProtoReflect.Descriptor instead.
func (*ListExecutionsReq) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{9}
}

func (x *ListExecutionsReq) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *ListExecutionsReq) GetStatus() ExecStatus {
	if x != nil {
		return x.Status
	}
	return ExecStatus_PENDING
}

func (x *ListExecutionsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListExecutionsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 列举执行历史响应
type ListExecutionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ExecutionRecord     `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsResp) Reset() {
	*x = ListExecutionsResp{}
	mi := &file_cronjob_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsResp) ProtoMessage() {}

func (x *ListExecutionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsResp.ProtoReflect.Descriptor instead.
func (*ListExecutionsResp) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{10}
}

func (x *ListExecutionsResp) GetRecords() []*ExecutionRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListExecutionsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 手动触发执行请求
type TriggerOnceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	TaskName      string                 `protobuf:"bytes,2,opt,name=taskName,proto3" json:"taskName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerOnceReq) Reset() {
	*x = TriggerOnceReq{}
	mi := &file_cronjob_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerOnceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerOnceReq) ProtoMessage() {}

func (x *TriggerOnceReq) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerOnceReq.ProtoReflect.Descriptor instead.
func (*TriggerOnceReq) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{11}
}

func (x *TriggerOnceReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TriggerOnceReq) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

// 手动触发执行响应
type TriggerOnceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   int64                  `protobuf:"varint,1,opt,name=executionId,proto3" json:"executionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerOnceResp) Reset() {
	*x = TriggerOnceResp{}
	mi := &file_cronjob_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerOnceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerOnceResp) ProtoMessage() {}

func (x *TriggerOnceResp) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerOnceResp.ProtoReflect.Descriptor instead.
func (*TriggerOnceResp) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{12}
}

func (x *TriggerOnceResp) GetExecutionId() int64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

// 重试任务请求
type RetryTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   int64                  `protobuf:"varint,1,opt,name=executionId,proto3" json:"executionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskReq) Reset() {
	*x = RetryTaskReq{}
	mi := &file_cronjob_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskReq) ProtoMessage() {}

func (x *RetryTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskReq.ProtoReflect.Descriptor instead.
func (*RetryTaskReq) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{13}
}

func (x *RetryTaskReq) GetExecutionId() int64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

// 重试任务响应
type RetryTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskResp) Reset() {
	*x = RetryTaskResp{}
	mi := &file_cronjob_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskResp) ProtoMessage() {}

func (x *RetryTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskResp.ProtoReflect.Descriptor instead.
func (*RetryTaskResp) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{14}
}

func (x *RetryTaskResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// 设置任务启用/禁用请求
type SetTaskEnabledReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskEnabledReq) Reset() {
	*x = SetTaskEnabledReq{}
	mi := &file_cronjob_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskEnabledReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskEnabledReq) ProtoMessage() {}

func (x *SetTaskEnabledReq) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskEnabledReq.ProtoReflect.Descriptor instead.
func (*SetTaskEnabledReq) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{15}
}

func (x *SetTaskEnabledReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *SetTaskEnabledReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetTaskEnabledReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// 设置任务启用/禁用响应
type SetTaskEnabledResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskEnabledResp) Reset() {
	*x = SetTaskEnabledResp{}
	mi := &file_cronjob_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskEnabledResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskEnabledResp) ProtoMessage() {}

func (x *SetTaskEnabledResp) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskEnabledResp.ProtoReflect.Descriptor instead.
func (*SetTaskEnabledResp) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{16}
}

func (x *SetTaskEnabledResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// 任务统计请求
type TaskStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskName      string                 `protobuf:"bytes,1,opt,name=taskName,proto3" json:"taskName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatsReq) Reset() {
	*x = TaskStatsReq{}
	mi := &file_cronjob_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatsReq) ProtoMessage() {}

func (x *TaskStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatsReq.ProtoReflect.Descriptor instead.
func (*TaskStatsReq) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{17}
}

func (x *TaskStatsReq) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

// 任务统计响应
type TaskStatsResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskName        string                 `protobuf:"bytes,1,opt,name=taskName,proto3" json:"taskName,omitempty"`
	TotalExecutions int64                  `protobuf:"varint,2,opt,name=totalExecutions,proto3" json:"totalExecutions,omitempty"`
	SuccessCount    int64                  `protobuf:"varint,3,opt,name=successCount,proto3" json:"successCount,omitempty"`
	FailedCount     int64                  `protobuf:"varint,4,opt,name=failedCount,proto3" json:"failedCount,omitempty"`
	RunningCount    int64                  `protobuf:"varint,5,opt,name=runningCount,proto3" json:"runningCount,omitempty"`
	LastExecutedAt  int64                  `protobuf:"varint,6,opt,name=lastExecutedAt,proto3" json:"lastExecutedAt,omitempty"`
	LastStatus      ExecStatus             `protobuf:"varint,7,opt,name=lastStatus,proto3,enum=cronjob.ExecStatus" json:"lastStatus,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskStatsResp) Reset() {
	*x = TaskStatsResp{}
	mi := &file_cronjob_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatsResp) ProtoMessage() {}

func (x *TaskStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_cronjob_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatsResp.ProtoReflect.Descriptor instead.
func (*TaskStatsResp) Descriptor() ([]byte, []int) {
	return file_cronjob_proto_rawDescGZIP(), []int{18}
}

func (x *TaskStatsResp) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskStatsResp) GetTotalExecutions() int64 {
	if x != nil {
		return x.TotalExecutions
	}
	return 0
}

func (x *TaskStatsResp) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *TaskStatsResp) GetFailedCount() int64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *TaskStatsResp) GetRunningCount() int64 {
	if x != nil {
		return x.RunningCount
	}
	return 0
}

func (x *TaskStatsResp) GetLastExecutedAt() int64 {
	if x != nil {
		return x.LastExecutedAt
	}
	return 0
}

func (x *TaskStatsResp) GetLastStatus() ExecStatus {
	if x != nil {
		return x.LastStatus
	}
	return ExecStatus_PENDING
}

var File_cronjob_proto protoreflect.FileDescriptor

const file_cronjob_proto_rawDesc = "" +
	"\n" +
	"\rcronjob.proto\x12\acronjob\"O\n" +
	"\vRetryPolicy\x12\x1e\n" +
	"\n" +
	"maxRetries\x18\x01 \x01(\x05R\n" +
	"maxRetries\x12 \n" +
	"\vintervalSec\x18\x02 \x01(\x05R\vintervalSec\"\x8a\x02\n" +
	"\x0fRegisterTaskReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcronExpr\x18\x02 \x01(\tR\bcronExpr\x123\n" +
	"\n" +
	"targetType\x18\x03 \x01(\x0e2\x13.cronjob.TargetTypeR\n" +
	"targetType\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12 \n" +
	"\vrequestBody\x18\x05 \x01(\tR\vrequestBody\x126\n" +
	"\vretryPolicy\x18\x06 \x01(\v2\x14.cronjob.RetryPolicyR\vretryPolicy\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"\"\n" +
	"\x10RegisterTaskResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"'\n" +
	"\x11UnregisterTaskReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"$\n" +
	"\x12UnregisterTaskResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xec\x02\n" +
	"\bTaskInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcronExpr\x18\x02 \x01(\tR\bcronExpr\x123\n" +
	"\n" +
	"targetType\x18\x03 \x01(\x0e2\x13.cronjob.TargetTypeR\n" +
	"targetType\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12 \n" +
	"\vrequestBody\x18\x05 \x01(\tR\vrequestBody\x126\n" +
	"\vretryPolicy\x18\x06 \x01(\v2\x14.cronjob.RetryPolicyR\vretryPolicy\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12+\n" +
	"\x06status\x18\b \x01(\x0e2\x13.cronjob.TaskStatusR\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\t \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\n" +
	" \x01(\x03R\tupdatedAt\">\n" +
	"\fListTasksReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"N\n" +
	"\rListTasksResp\x12'\n" +
	"\x05tasks\x18\x01 \x03(\v2\x11.cronjob.TaskInfoR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xd8\x02\n" +
	"\x0fExecutionRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\btaskName\x18\x02 \x01(\tR\btaskName\x12 \n" +
	"\vscheduledAt\x18\x03 \x01(\x03R\vscheduledAt\x12\x1c\n" +
	"\tstartedAt\x18\x04 \x01(\x03R\tstartedAt\x12\x1e\n" +
	"\n" +
	"finishedAt\x18\x05 \x01(\x03R\n" +
	"finishedAt\x12+\n" +
	"\x06status\x18\x06 \x01(\x0e2\x13.cronjob.ExecStatusR\x06status\x12\x1e\n" +
	"\n" +
	"retryCount\x18\a \x01(\x05R\n" +
	"retryCount\x12\x1e\n" +
	"\n" +
	"maxRetries\x18\b \x01(\x05R\n" +
	"maxRetries\x12\x16\n" +
	"\x06result\x18\t \x01(\tR\x06result\x12\x18\n" +
	"\atraceId\x18\n" +
	" \x01(\tR\atraceId\x12\x1a\n" +
	"\bexecNode\x18\v \x01(\tR\bexecNode\"\x8c\x01\n" +
	"\x11ListExecutionsReq\x12\x1a\n" +
	"\btaskName\x18\x01 \x01(\tR\btaskName\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.cronjob.ExecStatusR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\"^\n" +
	"\x12ListExecutionsResp\x122\n" +
	"\arecords\x18\x01 \x03(\v2\x18.cronjob.ExecutionRecordR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"D\n" +
	"\x0eTriggerOnceReq\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\x03R\x06taskId\x12\x1a\n" +
	"\btaskName\x18\x02 \x01(\tR\btaskName\"3\n" +
	"\x0fTriggerOnceResp\x12 \n" +
	"\vexecutionId\x18\x01 \x01(\x03R\vexecutionId\"0\n" +
	"\fRetryTaskReq\x12 \n" +
	"\vexecutionId\x18\x01 \x01(\x03R\vexecutionId\"\x1f\n" +
	"\rRetryTaskResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"Y\n" +
	"\x11SetTaskEnabledReq\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\x03R\x06taskId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"$\n" +
	"\x12SetTaskEnabledResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"*\n" +
	"\fTaskStatsReq\x12\x1a\n" +
	"\btaskName\x18\x01 \x01(\tR\btaskName\"\x9c\x02\n" +
	"\rTaskStatsResp\x12\x1a\n" +
	"\btaskName\x18\x01 \x01(\tR\btaskName\x12(\n" +
	"\x0ftotalExecutions\x18\x02 \x01(\x03R\x0ftotalExecutions\x12\"\n" +
	"\fsuccessCount\x18\x03 \x01(\x03R\fsuccessCount\x12 \n" +
	"\vfailedCount\x18\x04 \x01(\x03R\vfailedCount\x12\"\n" +
	"\frunningCount\x18\x05 \x01(\x03R\frunningCount\x12&\n" +
	"\x0elastExecutedAt\x18\x06 \x01(\x03R\x0elastExecutedAt\x123\n" +
	"\n" +
	"lastStatus\x18\a \x01(\x0e2\x13.cronjob.ExecStatusR\n" +
	"lastStatus* \n" +
	"\n" +
	"TargetType\x12\b\n" +
	"\x04GRPC\x10\x00\x12\b\n" +
	"\x04HTTP\x10\x01*1\n" +
	"\n" +
	"TaskStatus\x12\x11\n" +
	"\rTASK_DISABLED\x10\x00\x12\x10\n" +
	"\fTASK_ENABLED\x10\x01*M\n" +
	"\n" +
	"ExecStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\f\n" +
	"\bRETRYING\x10\x042\xa8\x04\n" +
	"\aCronJob\x12C\n" +
	"\fRegisterTask\x12\x18.cronjob.RegisterTaskReq\x1a\x19.cronjob.RegisterTaskResp\x12I\n" +
	"\x0eUnregisterTask\x12\x1a.cronjob.UnregisterTaskReq\x1a\x1b.cronjob.UnregisterTaskResp\x12:\n" +
	"\tListTasks\x12\x15.cronjob.ListTasksReq\x1a\x16.cronjob.ListTasksResp\x12I\n" +
	"\x0eSetTaskEnabled\x12\x1a.cronjob.SetTaskEnabledReq\x1a\x1b.cronjob.SetTaskEnabledResp\x12I\n" +
	"\x0eListExecutions\x12\x1a.cronjob.ListExecutionsReq\x1a\x1b.cronjob.ListExecutionsResp\x12@\n" +
	"\vTriggerOnce\x12\x17.cronjob.TriggerOnceReq\x1a\x18.cronjob.TriggerOnceResp\x12:\n" +
	"\tRetryTask\x12\x15.cronjob.RetryTaskReq\x1a\x16.cronjob.RetryTaskResp\x12=\n" +
	"\fGetTaskStats\x12\x15.cronjob.TaskStatsReq\x1a\x16.cronjob.TaskStatsRespB\vZ\t./cronjobb\x06proto3"

var (
	file_cronjob_proto_rawDescOnce sync.Once
	file_cronjob_proto_rawDescData []byte
)

func file_cronjob_proto_rawDescGZIP() []byte {
	file_cronjob_proto_rawDescOnce.Do(func() {
		file_cronjob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cronjob_proto_rawDesc), len(file_cronjob_proto_rawDesc)))
	})
	return file_cronjob_proto_rawDescData
}

var file_cronjob_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_cronjob_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_cronjob_proto_goTypes = []any{
	(TargetType)(0),            // 0: cronjob.TargetType
	(TaskStatus)(0),            // 1: cronjob.TaskStatus
	(ExecStatus)(0),            // 2: cronjob.ExecStatus
	(*RetryPolicy)(nil),        // 3: cronjob.RetryPolicy
	(*RegisterTaskReq)(nil),    // 4: cronjob.RegisterTaskReq
	(*RegisterTaskResp)(nil),   // 5: cronjob.RegisterTaskResp
	(*UnregisterTaskReq)(nil),  // 6: cronjob.UnregisterTaskReq
	(*UnregisterTaskResp)(nil), // 7: cronjob.UnregisterTaskResp
	(*TaskInfo)(nil),           // 8: cronjob.TaskInfo
	(*ListTasksReq)(nil),       // 9: cronjob.ListTasksReq
	(*ListTasksResp)(nil),      // 10: cronjob.ListTasksResp
	(*ExecutionRecord)(nil),    // 11: cronjob.ExecutionRecord
	(*ListExecutionsReq)(nil),  // 12: cronjob.ListExecutionsReq
	(*ListExecutionsResp)(nil), // 13: cronjob.ListExecutionsResp
	(*TriggerOnceReq)(nil),     // 14: cronjob.TriggerOnceReq
	(*TriggerOnceResp)(nil),    // 15: cronjob.TriggerOnceResp
	(*RetryTaskReq)(nil),       // 16: cronjob.RetryTaskReq
	(*RetryTaskResp)(nil),      // 17: cronjob.RetryTaskResp
	(*SetTaskEnabledReq)(nil),  // 18: cronjob.SetTaskEnabledReq
	(*SetTaskEnabledResp)(nil), // 19: cronjob.SetTaskEnabledResp
	(*TaskStatsReq)(nil),       // 20: cronjob.TaskStatsReq
	(*TaskStatsResp)(nil),      // 21: cronjob.TaskStatsResp
}
var file_cronjob_proto_depIdxs = []int32{
	0,  // 0: cronjob.RegisterTaskReq.targetType:type_name -> cronjob.TargetType
	3,  // 1: cronjob.RegisterTaskReq.retryPolicy:type_name -> cronjob.RetryPolicy
	0,  // 2: cronjob.TaskInfo.targetType:type_name -> cronjob.TargetType
	3,  // 3: cronjob.TaskInfo.retryPolicy:type_name -> cronjob.RetryPolicy
	1,  // 4: cronjob.TaskInfo.status:type_name -> cronjob.TaskStatus
	8,  // 5: cronjob.ListTasksResp.tasks:type_name -> cronjob.TaskInfo
	2,  // 6: cronjob.ExecutionRecord.status:type_name -> cronjob.ExecStatus
	2,  // 7: cronjob.ListExecutionsReq.status:type_name -> cronjob.ExecStatus
	11, // 8: cronjob.ListExecutionsResp.records:type_name -> cronjob.ExecutionRecord
	2,  // 9: cronjob.TaskStatsResp.lastStatus:type_name -> cronjob.ExecStatus
	4,  // 10: cronjob.CronJob.RegisterTask:input_type -> cronjob.RegisterTaskReq
	6,  // 11: cronjob.CronJob.UnregisterTask:input_type -> cronjob.UnregisterTaskReq
	9,  // 12: cronjob.CronJob.ListTasks:input_type -> cronjob.ListTasksReq
	18, // 13: cronjob.CronJob.SetTaskEnabled:input_type -> cronjob.SetTaskEnabledReq
	12, // 14: cronjob.CronJob.ListExecutions:input_type -> cronjob.ListExecutionsReq
	14, // 15: cronjob.CronJob.TriggerOnce:input_type -> cronjob.TriggerOnceReq
	16, // 16: cronjob.CronJob.RetryTask:input_type -> cronjob.RetryTaskReq
	20, // 17: cronjob.CronJob.GetTaskStats:input_type -> cronjob.TaskStatsReq
	5,  // 18: cronjob.CronJob.RegisterTask:output_type -> cronjob.RegisterTaskResp
	7,  // 19: cronjob.CronJob.UnregisterTask:output_type -> cronjob.UnregisterTaskResp
	10, // 20: cronjob.CronJob.ListTasks:output_type -> cronjob.ListTasksResp
	19, // 21: cronjob.CronJob.SetTaskEnabled:output_type -> cronjob.SetTaskEnabledResp
	13, // 22: cronjob.CronJob.ListExecutions:output_type -> cronjob.ListExecutionsResp
	15, // 23: cronjob.CronJob.TriggerOnce:output_type -> cronjob.TriggerOnceResp
	17, // 24: cronjob.CronJob.RetryTask:output_type -> cronjob.RetryTaskResp
	21, // 25: cronjob.CronJob.GetTaskStats:output_type -> cronjob.TaskStatsResp
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cronjob_proto_init() }
func file_cronjob_proto_init() {
	if File_cronjob_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cronjob_proto_rawDesc), len(file_cronjob_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cronjob_proto_goTypes,
		DependencyIndexes: file_cronjob_proto_depIdxs,
		EnumInfos:         file_cronjob_proto_enumTypes,
		MessageInfos:      file_cronjob_proto_msgTypes,
	}.Build()
	File_cronjob_proto = out.File
	file_cronjob_proto_goTypes = nil
	file_cronjob_proto_depIdxs = nil
}
