// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: cronjob.proto

package cronjob

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CronJob_RegisterTask_FullMethodName   = "/cronjob.CronJob/RegisterTask"
	CronJob_UnregisterTask_FullMethodName = "/cronjob.CronJob/UnregisterTask"
	CronJob_ListTasks_FullMethodName      = "/cronjob.CronJob/ListTasks"
	CronJob_SetTaskEnabled_FullMethodName = "/cronjob.CronJob/SetTaskEnabled"
	CronJob_ListExecutions_FullMethodName = "/cronjob.CronJob/ListExecutions"
	CronJob_TriggerOnce_FullMethodName    = "/cronjob.CronJob/TriggerOnce"
	CronJob_RetryTask_FullMethodName      = "/cronjob.CronJob/RetryTask"
	CronJob_GetTaskStats_FullMethodName   = "/cronjob.CronJob/GetTaskStats"
)

// CronJobClient is the client API for CronJob service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CronJobClient interface {
	// 任务管理
	RegisterTask(ctx context.Context, in *RegisterTaskReq, opts ...grpc.CallOption) (*RegisterTaskResp, error)
	UnregisterTask(ctx context.Context, in *UnregisterTaskReq, opts ...grpc.CallOption) (*UnregisterTaskResp, error)
	ListTasks(ctx context.Context, in *ListTasksReq, opts ...grpc.CallOption) (*ListTasksResp, error)
	SetTaskEnabled(ctx context.Context, in *SetTaskEnabledReq, opts ...grpc.CallOption) (*SetTaskEnabledResp, error)
	// 执行历史
	ListExecutions(ctx context.Context, in *ListExecutionsReq, opts ...grpc.CallOption) (*ListExecutionsResp, error)
	// 任务操作
	TriggerOnce(ctx context.Context, in *TriggerOnceReq, opts ...grpc.CallOption) (*TriggerOnceResp, error)
	RetryTask(ctx context.Context, in *RetryTaskReq, opts ...grpc.CallOption) (*RetryTaskResp, error)
	// 任务监控
	GetTaskStats(ctx context.Context, in *TaskStatsReq, opts ...grpc.CallOption) (*TaskStatsResp, error)
}

type cronJobClient struct {
	cc grpc.ClientConnInterface
}

func NewCronJobClient(cc grpc.ClientConnInterface) CronJobClient {
	return &cronJobClient{cc}
}

func (c *cronJobClient) RegisterTask(ctx context.Context, in *RegisterTaskReq, opts ...grpc.CallOption) (*RegisterTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTaskResp)
	err := c.cc.Invoke(ctx, CronJob_RegisterTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronJobClient) UnregisterTask(ctx context.Context, in *UnregisterTaskReq, opts ...grpc.CallOption) (*UnregisterTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterTaskResp)
	err := c.cc.Invoke(ctx, CronJob_UnregisterTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronJobClient) ListTasks(ctx context.Context, in *ListTasksReq, opts ...grpc.CallOption) (*ListTasksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResp)
	err := c.cc.Invoke(ctx, CronJob_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronJobClient) SetTaskEnabled(ctx context.Context, in *SetTaskEnabledReq, opts ...grpc.CallOption) (*SetTaskEnabledResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTaskEnabledResp)
	err := c.cc.Invoke(ctx, CronJob_SetTaskEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronJobClient) ListExecutions(ctx context.Context, in *ListExecutionsReq, opts ...grpc.CallOption) (*ListExecutionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExecutionsResp)
	err := c.cc.Invoke(ctx, CronJob_ListExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronJobClient) TriggerOnce(ctx context.Context, in *TriggerOnceReq, opts ...grpc.CallOption) (*TriggerOnceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerOnceResp)
	err := c.cc.Invoke(ctx, CronJob_TriggerOnce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronJobClient) RetryTask(ctx context.Context, in *RetryTaskReq, opts ...grpc.CallOption) (*RetryTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryTaskResp)
	err := c.cc.Invoke(ctx, CronJob_RetryTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronJobClient) GetTaskStats(ctx context.Context, in *TaskStatsReq, opts ...grpc.CallOption) (*TaskStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatsResp)
	err := c.cc.Invoke(ctx, CronJob_GetTaskStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CronJobServer is the server API for CronJob service.
// All implementations must embed UnimplementedCronJobServer
// for forward compatibility.
type CronJobServer interface {
	// 任务管理
	RegisterTask(context.Context, *RegisterTaskReq) (*RegisterTaskResp, error)
	UnregisterTask(context.Context, *UnregisterTaskReq) (*UnregisterTaskResp, error)
	ListTasks(context.Context, *ListTasksReq) (*ListTasksResp, error)
	SetTaskEnabled(context.Context, *SetTaskEnabledReq) (*SetTaskEnabledResp, error)
	// 执行历史
	ListExecutions(context.Context, *ListExecutionsReq) (*ListExecutionsResp, error)
	// 任务操作
	TriggerOnce(context.Context, *TriggerOnceReq) (*TriggerOnceResp, error)
	RetryTask(context.Context, *RetryTaskReq) (*RetryTaskResp, error)
	// 任务监控
	GetTaskStats(context.Context, *TaskStatsReq) (*TaskStatsResp, error)
	mustEmbedUnimplementedCronJobServer()
}

// UnimplementedCronJobServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCronJobServer struct{}

func (UnimplementedCronJobServer) RegisterTask(context.Context, *RegisterTaskReq) (*RegisterTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTask not implemented")
}
func (UnimplementedCronJobServer) UnregisterTask(context.Context, *UnregisterTaskReq) (*UnregisterTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterTask not implemented")
}
func (UnimplementedCronJobServer) ListTasks(context.Context, *ListTasksReq) (*ListTasksResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedCronJobServer) SetTaskEnabled(context.Context, *SetTaskEnabledReq) (*SetTaskEnabledResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTaskEnabled not implemented")
}
func (UnimplementedCronJobServer) ListExecutions(context.Context, *ListExecutionsReq) (*ListExecutionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExecutions not implemented")
}
func (UnimplementedCronJobServer) TriggerOnce(context.Context, *TriggerOnceReq) (*TriggerOnceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerOnce not implemented")
}
func (UnimplementedCronJobServer) RetryTask(context.Context, *RetryTaskReq) (*RetryTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryTask not implemented")
}
func (UnimplementedCronJobServer) GetTaskStats(context.Context, *TaskStatsReq) (*TaskStatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStats not implemented")
}
func (UnimplementedCronJobServer) mustEmbedUnimplementedCronJobServer() {}
func (UnimplementedCronJobServer) testEmbeddedByValue()                 {}

// UnsafeCronJobServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CronJobServer will
// result in compilation errors.
type UnsafeCronJobServer interface {
	mustEmbedUnimplementedCronJobServer()
}

func RegisterCronJobServer(s grpc.ServiceRegistrar, srv CronJobServer) {
	// If the following call panics, it indicates UnimplementedCronJobServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CronJob_ServiceDesc, srv)
}

func _CronJob_RegisterTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronJobServer).RegisterTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronJob_RegisterTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronJobServer).RegisterTask(ctx, req.(*RegisterTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronJob_UnregisterTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronJobServer).UnregisterTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronJob_UnregisterTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronJobServer).UnregisterTask(ctx, req.(*UnregisterTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronJob_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronJobServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronJob_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronJobServer).ListTasks(ctx, req.(*ListTasksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronJob_SetTaskEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTaskEnabledReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronJobServer).SetTaskEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronJob_SetTaskEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronJobServer).SetTaskEnabled(ctx, req.(*SetTaskEnabledReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronJob_ListExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExecutionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronJobServer).ListExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronJob_ListExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronJobServer).ListExecutions(ctx, req.(*ListExecutionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronJob_TriggerOnce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerOnceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronJobServer).TriggerOnce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronJob_TriggerOnce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronJobServer).TriggerOnce(ctx, req.(*TriggerOnceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronJob_RetryTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronJobServer).RetryTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronJob_RetryTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronJobServer).RetryTask(ctx, req.(*RetryTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronJob_GetTaskStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronJobServer).GetTaskStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronJob_GetTaskStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronJobServer).GetTaskStats(ctx, req.(*TaskStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CronJob_ServiceDesc is the grpc.ServiceDesc for CronJob service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CronJob_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cronjob.CronJob",
	HandlerType: (*CronJobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterTask",
			Handler:    _CronJob_RegisterTask_Handler,
		},
		{
			MethodName: "UnregisterTask",
			Handler:    _CronJob_UnregisterTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _CronJob_ListTasks_Handler,
		},
		{
			MethodName: "SetTaskEnabled",
			Handler:    _CronJob_SetTaskEnabled_Handler,
		},
		{
			MethodName: "ListExecutions",
			Handler:    _CronJob_ListExecutions_Handler,
		},
		{
			MethodName: "TriggerOnce",
			Handler:    _CronJob_TriggerOnce_Handler,
		},
		{
			MethodName: "RetryTask",
			Handler:    _CronJob_RetryTask_Handler,
		},
		{
			MethodName: "GetTaskStats",
			Handler:    _CronJob_GetTaskStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cronjob.proto",
}
