// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package server

import (
	"context"

	"order-rpc/internal/logic"
	"order-rpc/internal/svc"
	"order-rpc/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

// 订单支付提交
func (s *OrderServer) OrderCommitPay(ctx context.Context, in *order.OrderCommitPayReq) (*order.OrderCommitPayResp, error) {
	l := logic.NewOrderCommitPayLogic(ctx, s.svcCtx)
	return l.OrderCommitPay(in)
}

// 订单状态检测
func (s *OrderServer) OrderStateCheck(ctx context.Context, in *order.OrderStateCheckReq) (*order.OrderStateCheckResp, error) {
	l := logic.NewOrderStateCheckLogic(ctx, s.svcCtx)
	return l.OrderStateCheck(in)
}

// 创建订单
func (s *OrderServer) CreateOrder(ctx context.Context, in *order.CreateOrderReq) (*order.CreateOrderRsp, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

// 取消订单
func (s *OrderServer) CancelOrder(ctx context.Context, in *order.CancelOrderReq) (*order.CancelOrderRsp, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}
