// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: cronjob.proto

package cron_job_client

import (
	"context"

	"cronjob-rpc/cronjob"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExecutionRecord     = cronjob.ExecutionRecord
	ListExecutionsReq   = cronjob.ListExecutionsReq
	ListExecutionsResp  = cronjob.ListExecutionsResp
	ListTasksReq        = cronjob.ListTasksReq
	ListTasksResp       = cronjob.ListTasksResp
	RegisterTaskReq     = cronjob.RegisterTaskReq
	RegisterTaskResp    = cronjob.RegisterTaskResp
	ReportExecutionReq  = cronjob.ReportExecutionReq
	ReportExecutionResp = cronjob.ReportExecutionResp
	RetryPolicy         = cronjob.RetryPolicy
	RetryTaskReq        = cronjob.RetryTaskReq
	RetryTaskResp       = cronjob.RetryTaskResp
	SetTaskEnabledReq   = cronjob.SetTaskEnabledReq
	SetTaskEnabledResp  = cronjob.SetTaskEnabledResp
	TaskInfo            = cronjob.TaskInfo
	TaskStatsReq        = cronjob.TaskStatsReq
	TaskStatsResp       = cronjob.TaskStatsResp
	TriggerOnceReq      = cronjob.TriggerOnceReq
	TriggerOnceResp     = cronjob.TriggerOnceResp
	UnregisterTaskReq   = cronjob.UnregisterTaskReq
	UnregisterTaskResp  = cronjob.UnregisterTaskResp

	CronJob interface {
		// 任务管理
		RegisterTask(ctx context.Context, in *RegisterTaskReq, opts ...grpc.CallOption) (*RegisterTaskResp, error)
		UnregisterTask(ctx context.Context, in *UnregisterTaskReq, opts ...grpc.CallOption) (*UnregisterTaskResp, error)
		ListTasks(ctx context.Context, in *ListTasksReq, opts ...grpc.CallOption) (*ListTasksResp, error)
		SetTaskEnabled(ctx context.Context, in *SetTaskEnabledReq, opts ...grpc.CallOption) (*SetTaskEnabledResp, error)
		// 执行历史
		ListExecutions(ctx context.Context, in *ListExecutionsReq, opts ...grpc.CallOption) (*ListExecutionsResp, error)
		// 任务操作
		TriggerOnce(ctx context.Context, in *TriggerOnceReq, opts ...grpc.CallOption) (*TriggerOnceResp, error)
		RetryTask(ctx context.Context, in *RetryTaskReq, opts ...grpc.CallOption) (*RetryTaskResp, error)
		// 业务方回调
		ReportExecution(ctx context.Context, in *ReportExecutionReq, opts ...grpc.CallOption) (*ReportExecutionResp, error)
		// 任务监控
		GetTaskStats(ctx context.Context, in *TaskStatsReq, opts ...grpc.CallOption) (*TaskStatsResp, error)
	}

	defaultCronJob struct {
		cli zrpc.Client
	}
)

func NewCronJob(cli zrpc.Client) CronJob {
	return &defaultCronJob{
		cli: cli,
	}
}

// 任务管理
func (m *defaultCronJob) RegisterTask(ctx context.Context, in *RegisterTaskReq, opts ...grpc.CallOption) (*RegisterTaskResp, error) {
	client := cronjob.NewCronJobClient(m.cli.Conn())
	return client.RegisterTask(ctx, in, opts...)
}

func (m *defaultCronJob) UnregisterTask(ctx context.Context, in *UnregisterTaskReq, opts ...grpc.CallOption) (*UnregisterTaskResp, error) {
	client := cronjob.NewCronJobClient(m.cli.Conn())
	return client.UnregisterTask(ctx, in, opts...)
}

func (m *defaultCronJob) ListTasks(ctx context.Context, in *ListTasksReq, opts ...grpc.CallOption) (*ListTasksResp, error) {
	client := cronjob.NewCronJobClient(m.cli.Conn())
	return client.ListTasks(ctx, in, opts...)
}

func (m *defaultCronJob) SetTaskEnabled(ctx context.Context, in *SetTaskEnabledReq, opts ...grpc.CallOption) (*SetTaskEnabledResp, error) {
	client := cronjob.NewCronJobClient(m.cli.Conn())
	return client.SetTaskEnabled(ctx, in, opts...)
}

// 执行历史
func (m *defaultCronJob) ListExecutions(ctx context.Context, in *ListExecutionsReq, opts ...grpc.CallOption) (*ListExecutionsResp, error) {
	client := cronjob.NewCronJobClient(m.cli.Conn())
	return client.ListExecutions(ctx, in, opts...)
}

// 任务操作
func (m *defaultCronJob) TriggerOnce(ctx context.Context, in *TriggerOnceReq, opts ...grpc.CallOption) (*TriggerOnceResp, error) {
	client := cronjob.NewCronJobClient(m.cli.Conn())
	return client.TriggerOnce(ctx, in, opts...)
}

func (m *defaultCronJob) RetryTask(ctx context.Context, in *RetryTaskReq, opts ...grpc.CallOption) (*RetryTaskResp, error) {
	client := cronjob.NewCronJobClient(m.cli.Conn())
	return client.RetryTask(ctx, in, opts...)
}

// 业务方回调
func (m *defaultCronJob) ReportExecution(ctx context.Context, in *ReportExecutionReq, opts ...grpc.CallOption) (*ReportExecutionResp, error) {
	client := cronjob.NewCronJobClient(m.cli.Conn())
	return client.ReportExecution(ctx, in, opts...)
}

// 任务监控
func (m *defaultCronJob) GetTaskStats(ctx context.Context, in *TaskStatsReq, opts ...grpc.CallOption) (*TaskStatsResp, error) {
	client := cronjob.NewCronJobClient(m.cli.Conn())
	return client.GetTaskStats(ctx, in, opts...)
}
