// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: stock.proto

package stock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 查询单个商品库存请求
type QueryStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         int64                  `protobuf:"varint,1,opt,name=skuId,proto3" json:"skuId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStockReq) Reset() {
	*x = QueryStockReq{}
	mi := &file_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStockReq) ProtoMessage() {}

func (x *QueryStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStockReq.ProtoReflect.Descriptor instead.
func (*QueryStockReq) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{0}
}

func (x *QueryStockReq) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

// 单个商品库存信息
type StockInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SkuId          int64                  `protobuf:"varint,1,opt,name=skuId,proto3" json:"skuId,omitempty"`                   // SKU ID
	TotalStock     int64                  `protobuf:"varint,2,opt,name=totalStock,proto3" json:"totalStock,omitempty"`         // 总库存
	AvailableStock int64                  `protobuf:"varint,3,opt,name=availableStock,proto3" json:"availableStock,omitempty"` // 可用库存（可下单量）
	LockedStock    int64                  `protobuf:"varint,4,opt,name=lockedStock,proto3" json:"lockedStock,omitempty"`       // 锁定库存（被订单占用但未支付）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StockInfo) Reset() {
	*x = StockInfo{}
	mi := &file_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfo) ProtoMessage() {}

func (x *StockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfo.ProtoReflect.Descriptor instead.
func (*StockInfo) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{1}
}

func (x *StockInfo) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *StockInfo) GetTotalStock() int64 {
	if x != nil {
		return x.TotalStock
	}
	return 0
}

func (x *StockInfo) GetAvailableStock() int64 {
	if x != nil {
		return x.AvailableStock
	}
	return 0
}

func (x *StockInfo) GetLockedStock() int64 {
	if x != nil {
		return x.LockedStock
	}
	return 0
}

// 查询单个商品库存响应
type QueryStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockInfo     *StockInfo             `protobuf:"bytes,1,opt,name=stockInfo,proto3" json:"stockInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStockResp) Reset() {
	*x = QueryStockResp{}
	mi := &file_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStockResp) ProtoMessage() {}

func (x *QueryStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStockResp.ProtoReflect.Descriptor instead.
func (*QueryStockResp) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{2}
}

func (x *QueryStockResp) GetStockInfo() *StockInfo {
	if x != nil {
		return x.StockInfo
	}
	return nil
}

// 批量查询库存请求
type BatchQueryStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuIds        []int64                `protobuf:"varint,1,rep,packed,name=skuIds,proto3" json:"skuIds,omitempty"` // SKU ID 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchQueryStockReq) Reset() {
	*x = BatchQueryStockReq{}
	mi := &file_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchQueryStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchQueryStockReq) ProtoMessage() {}

func (x *BatchQueryStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchQueryStockReq.ProtoReflect.Descriptor instead.
func (*BatchQueryStockReq) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{3}
}

func (x *BatchQueryStockReq) GetSkuIds() []int64 {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

// 批量查询库存响应
type BatchQueryStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*StockInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"` // 库存信息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchQueryStockResp) Reset() {
	*x = BatchQueryStockResp{}
	mi := &file_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchQueryStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchQueryStockResp) ProtoMessage() {}

func (x *BatchQueryStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchQueryStockResp.ProtoReflect.Descriptor instead.
func (*BatchQueryStockResp) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{4}
}

func (x *BatchQueryStockResp) GetList() []*StockInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// TCC Try：冻结库存请求（Phase 1 - 资源预留）
type TccTryDeductStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xid           string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`             // dtm 全局事务 ID（用于幂等去重 + 子事务屏障）
	TransType     string                 `protobuf:"bytes,2,opt,name=transType,proto3" json:"transType,omitempty"` // dtm 事务类型，固定为 "tcc"
	SkuId         int64                  `protobuf:"varint,3,opt,name=skuId,proto3" json:"skuId,omitempty"`        // 商品 SKU ID
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`  // 冻结数量
	OrderNo       string                 `protobuf:"bytes,5,opt,name=orderNo,proto3" json:"orderNo,omitempty"`     // 订单号（业务幂等键）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TccTryDeductStockReq) Reset() {
	*x = TccTryDeductStockReq{}
	mi := &file_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TccTryDeductStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TccTryDeductStockReq) ProtoMessage() {}

func (x *TccTryDeductStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TccTryDeductStockReq.ProtoReflect.Descriptor instead.
func (*TccTryDeductStockReq) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{5}
}

func (x *TccTryDeductStockReq) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

func (x *TccTryDeductStockReq) GetTransType() string {
	if x != nil {
		return x.TransType
	}
	return ""
}

func (x *TccTryDeductStockReq) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *TccTryDeductStockReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TccTryDeductStockReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

// TCC Confirm：确认扣减库存请求（Phase 2 - 提交，由 DTM 回调）
type TccConfirmDeductStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xid           string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`             // dtm 全局事务 ID
	TransType     string                 `protobuf:"bytes,2,opt,name=transType,proto3" json:"transType,omitempty"` // dtm 事务类型，固定为 "tcc"
	SkuId         int64                  `protobuf:"varint,3,opt,name=skuId,proto3" json:"skuId,omitempty"`        // 商品 SKU ID
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`  // 扣减数量
	OrderNo       string                 `protobuf:"bytes,5,opt,name=orderNo,proto3" json:"orderNo,omitempty"`     // 订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TccConfirmDeductStockReq) Reset() {
	*x = TccConfirmDeductStockReq{}
	mi := &file_stock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TccConfirmDeductStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TccConfirmDeductStockReq) ProtoMessage() {}

func (x *TccConfirmDeductStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TccConfirmDeductStockReq.ProtoReflect.Descriptor instead.
func (*TccConfirmDeductStockReq) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{6}
}

func (x *TccConfirmDeductStockReq) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

func (x *TccConfirmDeductStockReq) GetTransType() string {
	if x != nil {
		return x.TransType
	}
	return ""
}

func (x *TccConfirmDeductStockReq) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *TccConfirmDeductStockReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TccConfirmDeductStockReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

// TCC Cancel：释放库存请求（Phase 2 - 回滚，由 DTM 回调）
type TccCancelDeductStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xid           string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`             // dtm 全局事务 ID
	TransType     string                 `protobuf:"bytes,2,opt,name=transType,proto3" json:"transType,omitempty"` // dtm 事务类型，固定为 "tcc"
	SkuId         int64                  `protobuf:"varint,3,opt,name=skuId,proto3" json:"skuId,omitempty"`        // 商品 SKU ID
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`  // 释放数量
	OrderNo       string                 `protobuf:"bytes,5,opt,name=orderNo,proto3" json:"orderNo,omitempty"`     // 订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TccCancelDeductStockReq) Reset() {
	*x = TccCancelDeductStockReq{}
	mi := &file_stock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TccCancelDeductStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TccCancelDeductStockReq) ProtoMessage() {}

func (x *TccCancelDeductStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TccCancelDeductStockReq.ProtoReflect.Descriptor instead.
func (*TccCancelDeductStockReq) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{7}
}

func (x *TccCancelDeductStockReq) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

func (x *TccCancelDeductStockReq) GetTransType() string {
	if x != nil {
		return x.TransType
	}
	return ""
}

func (x *TccCancelDeductStockReq) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *TccCancelDeductStockReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TccCancelDeductStockReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

var File_stock_proto protoreflect.FileDescriptor

const file_stock_proto_rawDesc = "" +
	"\n" +
	"\vstock.proto\x12\x05stock\x1a\x1bgoogle/protobuf/empty.proto\"%\n" +
	"\rQueryStockReq\x12\x14\n" +
	"\x05skuId\x18\x01 \x01(\x03R\x05skuId\"\x8b\x01\n" +
	"\tStockInfo\x12\x14\n" +
	"\x05skuId\x18\x01 \x01(\x03R\x05skuId\x12\x1e\n" +
	"\n" +
	"totalStock\x18\x02 \x01(\x03R\n" +
	"totalStock\x12&\n" +
	"\x0eavailableStock\x18\x03 \x01(\x03R\x0eavailableStock\x12 \n" +
	"\vlockedStock\x18\x04 \x01(\x03R\vlockedStock\"@\n" +
	"\x0eQueryStockResp\x12.\n" +
	"\tstockInfo\x18\x01 \x01(\v2\x10.stock.StockInfoR\tstockInfo\",\n" +
	"\x12BatchQueryStockReq\x12\x16\n" +
	"\x06skuIds\x18\x01 \x03(\x03R\x06skuIds\";\n" +
	"\x13BatchQueryStockResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.stock.StockInfoR\x04list\"\x92\x01\n" +
	"\x14TccTryDeductStockReq\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\x12\x1c\n" +
	"\ttransType\x18\x02 \x01(\tR\ttransType\x12\x14\n" +
	"\x05skuId\x18\x03 \x01(\x03R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x18\n" +
	"\aorderNo\x18\x05 \x01(\tR\aorderNo\"\x96\x01\n" +
	"\x18TccConfirmDeductStockReq\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\x12\x1c\n" +
	"\ttransType\x18\x02 \x01(\tR\ttransType\x12\x14\n" +
	"\x05skuId\x18\x03 \x01(\x03R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x18\n" +
	"\aorderNo\x18\x05 \x01(\tR\aorderNo\"\x95\x01\n" +
	"\x17TccCancelDeductStockReq\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\x12\x1c\n" +
	"\ttransType\x18\x02 \x01(\tR\ttransType\x12\x14\n" +
	"\x05skuId\x18\x03 \x01(\x03R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x18\n" +
	"\aorderNo\x18\x05 \x01(\tR\aorderNo2\xbd\x02\n" +
	"\x05Stock\x12H\n" +
	"\x0fBatchQueryStock\x12\x19.stock.BatchQueryStockReq\x1a\x1a.stock.BatchQueryStockResp\x12H\n" +
	"\x11TccTryDeductStock\x12\x1b.stock.TccTryDeductStockReq\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x15TccConfirmDeductStock\x12\x1f.stock.TccConfirmDeductStockReq\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\x14TccCancelDeductStock\x12\x1e.stock.TccCancelDeductStockReq\x1a\x16.google.protobuf.EmptyB\tZ\a./stockb\x06proto3"

var (
	file_stock_proto_rawDescOnce sync.Once
	file_stock_proto_rawDescData []byte
)

func file_stock_proto_rawDescGZIP() []byte {
	file_stock_proto_rawDescOnce.Do(func() {
		file_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_proto_rawDesc), len(file_stock_proto_rawDesc)))
	})
	return file_stock_proto_rawDescData
}

var file_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_stock_proto_goTypes = []any{
	(*QueryStockReq)(nil),            // 0: stock.QueryStockReq
	(*StockInfo)(nil),                // 1: stock.StockInfo
	(*QueryStockResp)(nil),           // 2: stock.QueryStockResp
	(*BatchQueryStockReq)(nil),       // 3: stock.BatchQueryStockReq
	(*BatchQueryStockResp)(nil),      // 4: stock.BatchQueryStockResp
	(*TccTryDeductStockReq)(nil),     // 5: stock.TccTryDeductStockReq
	(*TccConfirmDeductStockReq)(nil), // 6: stock.TccConfirmDeductStockReq
	(*TccCancelDeductStockReq)(nil),  // 7: stock.TccCancelDeductStockReq
	(*emptypb.Empty)(nil),            // 8: google.protobuf.Empty
}
var file_stock_proto_depIdxs = []int32{
	1, // 0: stock.QueryStockResp.stockInfo:type_name -> stock.StockInfo
	1, // 1: stock.BatchQueryStockResp.list:type_name -> stock.StockInfo
	3, // 2: stock.Stock.BatchQueryStock:input_type -> stock.BatchQueryStockReq
	5, // 3: stock.Stock.TccTryDeductStock:input_type -> stock.TccTryDeductStockReq
	6, // 4: stock.Stock.TccConfirmDeductStock:input_type -> stock.TccConfirmDeductStockReq
	7, // 5: stock.Stock.TccCancelDeductStock:input_type -> stock.TccCancelDeductStockReq
	4, // 6: stock.Stock.BatchQueryStock:output_type -> stock.BatchQueryStockResp
	8, // 7: stock.Stock.TccTryDeductStock:output_type -> google.protobuf.Empty
	8, // 8: stock.Stock.TccConfirmDeductStock:output_type -> google.protobuf.Empty
	8, // 9: stock.Stock.TccCancelDeductStock:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stock_proto_init() }
func file_stock_proto_init() {
	if File_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_proto_rawDesc), len(file_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_proto_goTypes,
		DependencyIndexes: file_stock_proto_depIdxs,
		MessageInfos:      file_stock_proto_msgTypes,
	}.Build()
	File_stock_proto = out.File
	file_stock_proto_goTypes = nil
	file_stock_proto_depIdxs = nil
}
