// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: stock.proto

package stock

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Stock_DeductStock_FullMethodName           = "/stock.Stock/DeductStock"
	Stock_RollbackStock_FullMethodName         = "/stock.Stock/RollbackStock"
	Stock_QueryStock_FullMethodName            = "/stock.Stock/QueryStock"
	Stock_BatchQueryStock_FullMethodName       = "/stock.Stock/BatchQueryStock"
	Stock_TccTryDeductStock_FullMethodName     = "/stock.Stock/TccTryDeductStock"
	Stock_TccConfirmDeductStock_FullMethodName = "/stock.Stock/TccConfirmDeductStock"
	Stock_TccCancelDeductStock_FullMethodName  = "/stock.Stock/TccCancelDeductStock"
)

// StockClient is the client API for Stock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 库存服务
type StockClient interface {
	// Saga 正向：扣减库存（dtm Saga 全局事务中调用的 Action 分支）
	DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Saga 补偿：回滚库存（dtm Saga 全局事务失败时调用的 Compensate 分支）
	RollbackStock(ctx context.Context, in *RollbackStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 查询单个商品库存
	QueryStock(ctx context.Context, in *QueryStockReq, opts ...grpc.CallOption) (*QueryStockResp, error)
	// 批量查询商品库存
	BatchQueryStock(ctx context.Context, in *BatchQueryStockReq, opts ...grpc.CallOption) (*BatchQueryStockResp, error)
	// TCC Try：冻结库存（dtm TCC 全局事务 Try 阶段调用，预留资源）
	TccTryDeductStock(ctx context.Context, in *TccTryDeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// TCC Confirm：确认扣减库存（dtm TCC 全局事务 Confirm 阶段回调）
	TccConfirmDeductStock(ctx context.Context, in *TccConfirmDeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// TCC Cancel：释放库存（dtm TCC 全局事务 Cancel 阶段回调）
	TccCancelDeductStock(ctx context.Context, in *TccCancelDeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type stockClient struct {
	cc grpc.ClientConnInterface
}

func NewStockClient(cc grpc.ClientConnInterface) StockClient {
	return &stockClient{cc}
}

func (c *stockClient) DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Stock_DeductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockClient) RollbackStock(ctx context.Context, in *RollbackStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Stock_RollbackStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockClient) QueryStock(ctx context.Context, in *QueryStockReq, opts ...grpc.CallOption) (*QueryStockResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryStockResp)
	err := c.cc.Invoke(ctx, Stock_QueryStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockClient) BatchQueryStock(ctx context.Context, in *BatchQueryStockReq, opts ...grpc.CallOption) (*BatchQueryStockResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchQueryStockResp)
	err := c.cc.Invoke(ctx, Stock_BatchQueryStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockClient) TccTryDeductStock(ctx context.Context, in *TccTryDeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Stock_TccTryDeductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockClient) TccConfirmDeductStock(ctx context.Context, in *TccConfirmDeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Stock_TccConfirmDeductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockClient) TccCancelDeductStock(ctx context.Context, in *TccCancelDeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Stock_TccCancelDeductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockServer is the server API for Stock service.
// All implementations must embed UnimplementedStockServer
// for forward compatibility.
//
// 库存服务
type StockServer interface {
	// Saga 正向：扣减库存（dtm Saga 全局事务中调用的 Action 分支）
	DeductStock(context.Context, *DeductStockReq) (*emptypb.Empty, error)
	// Saga 补偿：回滚库存（dtm Saga 全局事务失败时调用的 Compensate 分支）
	RollbackStock(context.Context, *RollbackStockReq) (*emptypb.Empty, error)
	// 查询单个商品库存
	QueryStock(context.Context, *QueryStockReq) (*QueryStockResp, error)
	// 批量查询商品库存
	BatchQueryStock(context.Context, *BatchQueryStockReq) (*BatchQueryStockResp, error)
	// TCC Try：冻结库存（dtm TCC 全局事务 Try 阶段调用，预留资源）
	TccTryDeductStock(context.Context, *TccTryDeductStockReq) (*emptypb.Empty, error)
	// TCC Confirm：确认扣减库存（dtm TCC 全局事务 Confirm 阶段回调）
	TccConfirmDeductStock(context.Context, *TccConfirmDeductStockReq) (*emptypb.Empty, error)
	// TCC Cancel：释放库存（dtm TCC 全局事务 Cancel 阶段回调）
	TccCancelDeductStock(context.Context, *TccCancelDeductStockReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedStockServer()
}

// UnimplementedStockServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockServer struct{}

func (UnimplementedStockServer) DeductStock(context.Context, *DeductStockReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductStock not implemented")
}
func (UnimplementedStockServer) RollbackStock(context.Context, *RollbackStockReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackStock not implemented")
}
func (UnimplementedStockServer) QueryStock(context.Context, *QueryStockReq) (*QueryStockResp, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryStock not implemented")
}
func (UnimplementedStockServer) BatchQueryStock(context.Context, *BatchQueryStockReq) (*BatchQueryStockResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchQueryStock not implemented")
}
func (UnimplementedStockServer) TccTryDeductStock(context.Context, *TccTryDeductStockReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TccTryDeductStock not implemented")
}
func (UnimplementedStockServer) TccConfirmDeductStock(context.Context, *TccConfirmDeductStockReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TccConfirmDeductStock not implemented")
}
func (UnimplementedStockServer) TccCancelDeductStock(context.Context, *TccCancelDeductStockReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TccCancelDeductStock not implemented")
}
func (UnimplementedStockServer) mustEmbedUnimplementedStockServer() {}
func (UnimplementedStockServer) testEmbeddedByValue()               {}

// UnsafeStockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockServer will
// result in compilation errors.
type UnsafeStockServer interface {
	mustEmbedUnimplementedStockServer()
}

func RegisterStockServer(s grpc.ServiceRegistrar, srv StockServer) {
	// If the following call panics, it indicates UnimplementedStockServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Stock_ServiceDesc, srv)
}

func _Stock_DeductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServer).DeductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stock_DeductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServer).DeductStock(ctx, req.(*DeductStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stock_RollbackStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServer).RollbackStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stock_RollbackStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServer).RollbackStock(ctx, req.(*RollbackStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stock_QueryStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServer).QueryStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stock_QueryStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServer).QueryStock(ctx, req.(*QueryStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stock_BatchQueryStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchQueryStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServer).BatchQueryStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stock_BatchQueryStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServer).BatchQueryStock(ctx, req.(*BatchQueryStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stock_TccTryDeductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TccTryDeductStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServer).TccTryDeductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stock_TccTryDeductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServer).TccTryDeductStock(ctx, req.(*TccTryDeductStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stock_TccConfirmDeductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TccConfirmDeductStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServer).TccConfirmDeductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stock_TccConfirmDeductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServer).TccConfirmDeductStock(ctx, req.(*TccConfirmDeductStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stock_TccCancelDeductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TccCancelDeductStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServer).TccCancelDeductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stock_TccCancelDeductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServer).TccCancelDeductStock(ctx, req.(*TccCancelDeductStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Stock_ServiceDesc is the grpc.ServiceDesc for Stock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stock.Stock",
	HandlerType: (*StockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeductStock",
			Handler:    _Stock_DeductStock_Handler,
		},
		{
			MethodName: "RollbackStock",
			Handler:    _Stock_RollbackStock_Handler,
		},
		{
			MethodName: "QueryStock",
			Handler:    _Stock_QueryStock_Handler,
		},
		{
			MethodName: "BatchQueryStock",
			Handler:    _Stock_BatchQueryStock_Handler,
		},
		{
			MethodName: "TccTryDeductStock",
			Handler:    _Stock_TccTryDeductStock_Handler,
		},
		{
			MethodName: "TccConfirmDeductStock",
			Handler:    _Stock_TccConfirmDeductStock_Handler,
		},
		{
			MethodName: "TccCancelDeductStock",
			Handler:    _Stock_TccCancelDeductStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock.proto",
}
