// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: stock.proto

package stock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Saga 正向：扣减库存请求（dtm Saga Action）
type DeductStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`             // dtm 全局事务 ID（用于幂等去重 + 子事务屏障）
	TransType     string                 `protobuf:"bytes,2,opt,name=transType,proto3" json:"transType,omitempty"` // dtm 事务类型，固定为 "saga"
	SkuId         int64                  `protobuf:"varint,3,opt,name=skuId,proto3" json:"skuId,omitempty"`        // 商品 SKU ID
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`  // 扣减数量
	OrderNo       string                 `protobuf:"bytes,5,opt,name=orderNo,proto3" json:"orderNo,omitempty"`     // 订单号（业务幂等键）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockReq) Reset() {
	*x = DeductStockReq{}
	mi := &file_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockReq) ProtoMessage() {}

func (x *DeductStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockReq.ProtoReflect.Descriptor instead.
func (*DeductStockReq) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{0}
}

func (x *DeductStockReq) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *DeductStockReq) GetTransType() string {
	if x != nil {
		return x.TransType
	}
	return ""
}

func (x *DeductStockReq) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *DeductStockReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *DeductStockReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

// Saga 补偿：回滚库存请求（dtm Saga Compensate）
type RollbackStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`             // dtm 全局事务 ID
	TransType     string                 `protobuf:"bytes,2,opt,name=transType,proto3" json:"transType,omitempty"` // dtm 事务类型，固定为 "saga"
	SkuId         int64                  `protobuf:"varint,3,opt,name=skuId,proto3" json:"skuId,omitempty"`        // 商品 SKU ID
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`  // 回滚数量
	OrderNo       string                 `protobuf:"bytes,5,opt,name=orderNo,proto3" json:"orderNo,omitempty"`     // 订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackStockReq) Reset() {
	*x = RollbackStockReq{}
	mi := &file_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackStockReq) ProtoMessage() {}

func (x *RollbackStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackStockReq.ProtoReflect.Descriptor instead.
func (*RollbackStockReq) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{1}
}

func (x *RollbackStockReq) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *RollbackStockReq) GetTransType() string {
	if x != nil {
		return x.TransType
	}
	return ""
}

func (x *RollbackStockReq) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *RollbackStockReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RollbackStockReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

// 查询单个商品库存请求
type QueryStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         int64                  `protobuf:"varint,1,opt,name=skuId,proto3" json:"skuId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStockReq) Reset() {
	*x = QueryStockReq{}
	mi := &file_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStockReq) ProtoMessage() {}

func (x *QueryStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStockReq.ProtoReflect.Descriptor instead.
func (*QueryStockReq) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{2}
}

func (x *QueryStockReq) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

// 单个商品库存信息
type StockInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SkuId          int64                  `protobuf:"varint,1,opt,name=skuId,proto3" json:"skuId,omitempty"`                   // SKU ID
	TotalStock     int64                  `protobuf:"varint,2,opt,name=totalStock,proto3" json:"totalStock,omitempty"`         // 总库存
	AvailableStock int64                  `protobuf:"varint,3,opt,name=availableStock,proto3" json:"availableStock,omitempty"` // 可用库存（可下单量）
	LockedStock    int64                  `protobuf:"varint,4,opt,name=lockedStock,proto3" json:"lockedStock,omitempty"`       // 锁定库存（被订单占用但未支付）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StockInfo) Reset() {
	*x = StockInfo{}
	mi := &file_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfo) ProtoMessage() {}

func (x *StockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfo.ProtoReflect.Descriptor instead.
func (*StockInfo) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{3}
}

func (x *StockInfo) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *StockInfo) GetTotalStock() int64 {
	if x != nil {
		return x.TotalStock
	}
	return 0
}

func (x *StockInfo) GetAvailableStock() int64 {
	if x != nil {
		return x.AvailableStock
	}
	return 0
}

func (x *StockInfo) GetLockedStock() int64 {
	if x != nil {
		return x.LockedStock
	}
	return 0
}

// 查询单个商品库存响应
type QueryStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockInfo     *StockInfo             `protobuf:"bytes,1,opt,name=stockInfo,proto3" json:"stockInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStockResp) Reset() {
	*x = QueryStockResp{}
	mi := &file_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStockResp) ProtoMessage() {}

func (x *QueryStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStockResp.ProtoReflect.Descriptor instead.
func (*QueryStockResp) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{4}
}

func (x *QueryStockResp) GetStockInfo() *StockInfo {
	if x != nil {
		return x.StockInfo
	}
	return nil
}

// 批量查询库存请求
type BatchQueryStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuIds        []int64                `protobuf:"varint,1,rep,packed,name=skuIds,proto3" json:"skuIds,omitempty"` // SKU ID 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchQueryStockReq) Reset() {
	*x = BatchQueryStockReq{}
	mi := &file_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchQueryStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchQueryStockReq) ProtoMessage() {}

func (x *BatchQueryStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchQueryStockReq.ProtoReflect.Descriptor instead.
func (*BatchQueryStockReq) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{5}
}

func (x *BatchQueryStockReq) GetSkuIds() []int64 {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

// 批量查询库存响应
type BatchQueryStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*StockInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"` // 库存信息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchQueryStockResp) Reset() {
	*x = BatchQueryStockResp{}
	mi := &file_stock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchQueryStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchQueryStockResp) ProtoMessage() {}

func (x *BatchQueryStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchQueryStockResp.ProtoReflect.Descriptor instead.
func (*BatchQueryStockResp) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{6}
}

func (x *BatchQueryStockResp) GetList() []*StockInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_stock_proto protoreflect.FileDescriptor

const file_stock_proto_rawDesc = "" +
	"\n" +
	"\vstock.proto\x12\x05stock\x1a\x1bgoogle/protobuf/empty.proto\"\x8c\x01\n" +
	"\x0eDeductStockReq\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\x12\x1c\n" +
	"\ttransType\x18\x02 \x01(\tR\ttransType\x12\x14\n" +
	"\x05skuId\x18\x03 \x01(\x03R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x18\n" +
	"\aorderNo\x18\x05 \x01(\tR\aorderNo\"\x8e\x01\n" +
	"\x10RollbackStockReq\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\x12\x1c\n" +
	"\ttransType\x18\x02 \x01(\tR\ttransType\x12\x14\n" +
	"\x05skuId\x18\x03 \x01(\x03R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x18\n" +
	"\aorderNo\x18\x05 \x01(\tR\aorderNo\"%\n" +
	"\rQueryStockReq\x12\x14\n" +
	"\x05skuId\x18\x01 \x01(\x03R\x05skuId\"\x8b\x01\n" +
	"\tStockInfo\x12\x14\n" +
	"\x05skuId\x18\x01 \x01(\x03R\x05skuId\x12\x1e\n" +
	"\n" +
	"totalStock\x18\x02 \x01(\x03R\n" +
	"totalStock\x12&\n" +
	"\x0eavailableStock\x18\x03 \x01(\x03R\x0eavailableStock\x12 \n" +
	"\vlockedStock\x18\x04 \x01(\x03R\vlockedStock\"@\n" +
	"\x0eQueryStockResp\x12.\n" +
	"\tstockInfo\x18\x01 \x01(\v2\x10.stock.StockInfoR\tstockInfo\",\n" +
	"\x12BatchQueryStockReq\x12\x16\n" +
	"\x06skuIds\x18\x01 \x03(\x03R\x06skuIds\";\n" +
	"\x13BatchQueryStockResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.stock.StockInfoR\x04list2\x8c\x02\n" +
	"\x05Stock\x12<\n" +
	"\vDeductStock\x12\x15.stock.DeductStockReq\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\rRollbackStock\x12\x17.stock.RollbackStockReq\x1a\x16.google.protobuf.Empty\x129\n" +
	"\n" +
	"QueryStock\x12\x14.stock.QueryStockReq\x1a\x15.stock.QueryStockResp\x12H\n" +
	"\x0fBatchQueryStock\x12\x19.stock.BatchQueryStockReq\x1a\x1a.stock.BatchQueryStockRespB\tZ\a./stockb\x06proto3"

var (
	file_stock_proto_rawDescOnce sync.Once
	file_stock_proto_rawDescData []byte
)

func file_stock_proto_rawDescGZIP() []byte {
	file_stock_proto_rawDescOnce.Do(func() {
		file_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_proto_rawDesc), len(file_stock_proto_rawDesc)))
	})
	return file_stock_proto_rawDescData
}

var file_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_stock_proto_goTypes = []any{
	(*DeductStockReq)(nil),      // 0: stock.DeductStockReq
	(*RollbackStockReq)(nil),    // 1: stock.RollbackStockReq
	(*QueryStockReq)(nil),       // 2: stock.QueryStockReq
	(*StockInfo)(nil),           // 3: stock.StockInfo
	(*QueryStockResp)(nil),      // 4: stock.QueryStockResp
	(*BatchQueryStockReq)(nil),  // 5: stock.BatchQueryStockReq
	(*BatchQueryStockResp)(nil), // 6: stock.BatchQueryStockResp
	(*emptypb.Empty)(nil),       // 7: google.protobuf.Empty
}
var file_stock_proto_depIdxs = []int32{
	3, // 0: stock.QueryStockResp.stockInfo:type_name -> stock.StockInfo
	3, // 1: stock.BatchQueryStockResp.list:type_name -> stock.StockInfo
	0, // 2: stock.Stock.DeductStock:input_type -> stock.DeductStockReq
	1, // 3: stock.Stock.RollbackStock:input_type -> stock.RollbackStockReq
	2, // 4: stock.Stock.QueryStock:input_type -> stock.QueryStockReq
	5, // 5: stock.Stock.BatchQueryStock:input_type -> stock.BatchQueryStockReq
	7, // 6: stock.Stock.DeductStock:output_type -> google.protobuf.Empty
	7, // 7: stock.Stock.RollbackStock:output_type -> google.protobuf.Empty
	4, // 8: stock.Stock.QueryStock:output_type -> stock.QueryStockResp
	6, // 9: stock.Stock.BatchQueryStock:output_type -> stock.BatchQueryStockResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stock_proto_init() }
func file_stock_proto_init() {
	if File_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_proto_rawDesc), len(file_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_proto_goTypes,
		DependencyIndexes: file_stock_proto_depIdxs,
		MessageInfos:      file_stock_proto_msgTypes,
	}.Build()
	File_stock_proto = out.File
	file_stock_proto_goTypes = nil
	file_stock_proto_depIdxs = nil
}
