// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: cronjob.proto

package server

import (
	"context"

	"cronjob-rpc/cronjob"
	"cronjob-rpc/internal/logic"
	"cronjob-rpc/internal/svc"
)

type CronJobServer struct {
	svcCtx *svc.ServiceContext
	cronjob.UnimplementedCronJobServer
}

func NewCronJobServer(svcCtx *svc.ServiceContext) *CronJobServer {
	return &CronJobServer{
		svcCtx: svcCtx,
	}
}

// 任务管理
func (s *CronJobServer) RegisterTask(ctx context.Context, in *cronjob.RegisterTaskReq) (*cronjob.RegisterTaskResp, error) {
	l := logic.NewRegisterTaskLogic(ctx, s.svcCtx)
	return l.RegisterTask(in)
}

func (s *CronJobServer) UnregisterTask(ctx context.Context, in *cronjob.UnregisterTaskReq) (*cronjob.UnregisterTaskResp, error) {
	l := logic.NewUnregisterTaskLogic(ctx, s.svcCtx)
	return l.UnregisterTask(in)
}

func (s *CronJobServer) ListTasks(ctx context.Context, in *cronjob.ListTasksReq) (*cronjob.ListTasksResp, error) {
	l := logic.NewListTasksLogic(ctx, s.svcCtx)
	return l.ListTasks(in)
}

func (s *CronJobServer) SetTaskEnabled(ctx context.Context, in *cronjob.SetTaskEnabledReq) (*cronjob.SetTaskEnabledResp, error) {
	l := logic.NewSetTaskEnabledLogic(ctx, s.svcCtx)
	return l.SetTaskEnabled(in)
}

// 执行历史
func (s *CronJobServer) ListExecutions(ctx context.Context, in *cronjob.ListExecutionsReq) (*cronjob.ListExecutionsResp, error) {
	l := logic.NewListExecutionsLogic(ctx, s.svcCtx)
	return l.ListExecutions(in)
}

// 任务操作
func (s *CronJobServer) TriggerOnce(ctx context.Context, in *cronjob.TriggerOnceReq) (*cronjob.TriggerOnceResp, error) {
	l := logic.NewTriggerOnceLogic(ctx, s.svcCtx)
	return l.TriggerOnce(in)
}

func (s *CronJobServer) RetryTask(ctx context.Context, in *cronjob.RetryTaskReq) (*cronjob.RetryTaskResp, error) {
	l := logic.NewRetryTaskLogic(ctx, s.svcCtx)
	return l.RetryTask(in)
}

// 业务方回调
func (s *CronJobServer) ReportExecution(ctx context.Context, in *cronjob.ReportExecutionReq) (*cronjob.ReportExecutionResp, error) {
	l := logic.NewReportExecutionLogic(ctx, s.svcCtx)
	return l.ReportExecution(in)
}

// 任务监控
func (s *CronJobServer) GetTaskStats(ctx context.Context, in *cronjob.TaskStatsReq) (*cronjob.TaskStatsResp, error) {
	l := logic.NewGetTaskStatsLogic(ctx, s.svcCtx)
	return l.GetTaskStats(in)
}
