// Code generated by goctl. DO NOT EDIT.
// Source: stock.proto

package stockclient

import (
	"context"

	"stock-rpc/stock"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

type (
	DeductStockReq      = stock.DeductStockReq
	DeductStockResp     = emptypb.Empty
	RollbackStockReq    = stock.RollbackStockReq
	RollbackStockResp   = emptypb.Empty
	QueryStockReq       = stock.QueryStockReq
	QueryStockResp      = stock.QueryStockResp
	StockInfo           = stock.StockInfo
	BatchQueryStockReq  = stock.BatchQueryStockReq
	BatchQueryStockResp = stock.BatchQueryStockResp

	Stock interface {
		// Saga 正向：扣减库存
		DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
		// Saga 补偿：回滚库存
		RollbackStock(ctx context.Context, in *RollbackStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
		// 查询单个商品库存
		QueryStock(ctx context.Context, in *QueryStockReq, opts ...grpc.CallOption) (*QueryStockResp, error)
		// 批量查询商品库存
		BatchQueryStock(ctx context.Context, in *BatchQueryStockReq, opts ...grpc.CallOption) (*BatchQueryStockResp, error)
	}

	defaultStock struct {
		cli zrpc.Client
	}
)

func NewStock(cli zrpc.Client) Stock {
	return &defaultStock{
		cli: cli,
	}
}

// Saga 正向：扣减库存
func (m *defaultStock) DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.DeductStock(ctx, in, opts...)
}

// Saga 补偿：回滚库存
func (m *defaultStock) RollbackStock(ctx context.Context, in *RollbackStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.RollbackStock(ctx, in, opts...)
}

// 查询单个商品库存
func (m *defaultStock) QueryStock(ctx context.Context, in *QueryStockReq, opts ...grpc.CallOption) (*QueryStockResp, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.QueryStock(ctx, in, opts...)
}

// 批量查询商品库存
func (m *defaultStock) BatchQueryStock(ctx context.Context, in *BatchQueryStockReq, opts ...grpc.CallOption) (*BatchQueryStockResp, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.BatchQueryStock(ctx, in, opts...)
}
