// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package orderclient

import (
	"context"

	"order-rpc/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelOrderReq      = order.CancelOrderReq
	CancelOrderRsp      = order.CancelOrderRsp
	CreateOrderReq      = order.CreateOrderReq
	CreateOrderRsp      = order.CreateOrderRsp
	OrderCommitPayReq   = order.OrderCommitPayReq
	OrderCommitPayResp  = order.OrderCommitPayResp
	OrderCommon         = order.OrderCommon
	OrderStateCheckReq  = order.OrderStateCheckReq
	OrderStateCheckResp = order.OrderStateCheckResp
	TccCancelOrderReq   = order.TccCancelOrderReq
	TccCancelOrderResp  = order.TccCancelOrderResp
	TccConfirmOrderReq  = order.TccConfirmOrderReq
	TccConfirmOrderResp = order.TccConfirmOrderResp
	TccTryOrderReq      = order.TccTryOrderReq
	TccTryOrderResp     = order.TccTryOrderResp

	Order interface {
		// 订单支付提交
		OrderCommitPay(ctx context.Context, in *OrderCommitPayReq, opts ...grpc.CallOption) (*OrderCommitPayResp, error)
		// 订单状态检测
		OrderStateCheck(ctx context.Context, in *OrderStateCheckReq, opts ...grpc.CallOption) (*OrderStateCheckResp, error)
		// 创建订单
		CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderRsp, error)
		// 取消订单
		CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderRsp, error)
		// TCC Try：预留订单资源（由业务方/编排层在 Try 阶段调用）
		TccTryOrder(ctx context.Context, in *TccTryOrderReq, opts ...grpc.CallOption) (*TccTryOrderResp, error)
		// TCC Confirm：确认订单（由 DTM 在 Confirm 阶段回调）
		TccConfirmOrder(ctx context.Context, in *TccConfirmOrderReq, opts ...grpc.CallOption) (*TccConfirmOrderResp, error)
		// TCC Cancel：回滚订单（由 DTM 在 Cancel 阶段回调）
		TccCancelOrder(ctx context.Context, in *TccCancelOrderReq, opts ...grpc.CallOption) (*TccCancelOrderResp, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

// 订单支付提交
func (m *defaultOrder) OrderCommitPay(ctx context.Context, in *OrderCommitPayReq, opts ...grpc.CallOption) (*OrderCommitPayResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.OrderCommitPay(ctx, in, opts...)
}

// 订单状态检测
func (m *defaultOrder) OrderStateCheck(ctx context.Context, in *OrderStateCheckReq, opts ...grpc.CallOption) (*OrderStateCheckResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.OrderStateCheck(ctx, in, opts...)
}

// 创建订单
func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderRsp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

// 取消订单
func (m *defaultOrder) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderRsp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

// TCC Try：预留订单资源（由业务方/编排层在 Try 阶段调用）
func (m *defaultOrder) TccTryOrder(ctx context.Context, in *TccTryOrderReq, opts ...grpc.CallOption) (*TccTryOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.TccTryOrder(ctx, in, opts...)
}

// TCC Confirm：确认订单（由 DTM 在 Confirm 阶段回调）
func (m *defaultOrder) TccConfirmOrder(ctx context.Context, in *TccConfirmOrderReq, opts ...grpc.CallOption) (*TccConfirmOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.TccConfirmOrder(ctx, in, opts...)
}

// TCC Cancel：回滚订单（由 DTM 在 Cancel 阶段回调）
func (m *defaultOrder) TccCancelOrder(ctx context.Context, in *TccCancelOrderReq, opts ...grpc.CallOption) (*TccCancelOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.TccCancelOrder(ctx, in, opts...)
}
